// Auto-generated by sa-expert
// Source: pm/customer-self-service-round2.feature
// Technical feature: sa/sa-customer-self-service-round2.feature
// Project uses xUnit test classes rather than SpecFlow bindings; these are implementation skeletons.

using System;
using System.Threading.Tasks;

namespace PetSalon.SA.StepDefinitions;

public sealed class CustomerSelfServiceRound2Steps
{
    // TODO: Core test fixture
    // - SQLite in-memory PetSalonDbContext
    // - FakeClock / SequentialIdGenerator
    // - planned CustomerRegistrationService

    public Task OwnerAndPetNotesAreSavedInOneBatchAsync()
        => throw new NotImplementedException();

    public void CustomerFormExposesOwnerAndPetNoteControls()
        => throw new NotImplementedException();

    public Task MedicalHistoryAndOtherTextAreMappedAsync()
        => throw new NotImplementedException();

    public void NoneOfAboveIsMutuallyExclusive()
        => throw new NotImplementedException();

    public Task ChipStatesMapToExistingPetFieldsAsync(string chipStatus, string? chipData)
        => throw new NotImplementedException();

    public Task ChipNumberIsRequiredWhenStatusIsYesAsync()
        => throw new NotImplementedException();

    public Task InvalidSecondPetLeavesNoOwnerOrPetsAsync()
        => throw new NotImplementedException();

    public Task DuplicateNationalIdOrPhoneReturnsPotentialMatchesAsync(string matchedField)
        => throw new NotImplementedException();

    public Task CancelledDuplicateWarningKeepsFormInputAsync()
        => throw new NotImplementedException();

    public Task AllowedDuplicateUsesOneSaveChangesAsync()
        => throw new NotImplementedException();

    public Task BusySubmitDoesNotStartSecondCreateAsync()
        => throw new NotImplementedException();
}
