// Auto-generated by sa-expert
// Source: pm/owner-deletion.feature
// Technical feature: sa/sa-owner-deletion.feature
// Project uses xUnit test classes rather than SpecFlow bindings; these are implementation skeletons.

using System;
using System.Threading.Tasks;

namespace PetSalon.SA.StepDefinitions;

public sealed class OwnerDeletionSteps
{
    // TODO: Core test fixture
    // - SQLite in-memory PetSalonDbContext
    // - OwnerService with seeded Owner/Pet/Appointment/GroomingRecord graphs
    // TODO: WPF test fixture
    // - OwnerPageViewModel + FakeDialogService

    public void OwnerPageExposesDeleteOwnerButton()
        => throw new NotImplementedException();

    public Task ConfirmationIncludesOwnerNamePetCountAndIrreversibleWarningAsync()
        => throw new NotImplementedException();

    public Task CancelDoesNotCallDeleteAsync()
        => throw new NotImplementedException();

    public Task OwnerAndPetsWithoutHistoryAreDeletedWithOneSaveAsync()
        => throw new NotImplementedException();

    public Task AppointmentOrGroomingHistoryBlocksDeletionAsync(string historyType)
        => throw new NotImplementedException();

    public Task ViewModelDisplaysOwnerHasHistoryReasonAsync()
        => throw new NotImplementedException();

    public Task SuccessfulDeleteClearsSelectionAndRefreshesAsync()
        => throw new NotImplementedException();

    public Task FailedSaveLeavesOwnerAndPetsPersistedAsync()
        => throw new NotImplementedException();
}
