// Auto-generated by sa-expert
// Source: pm/shop-signature-pdf.feature
// Technical feature: sa/sa-shop-signature-pdf.feature
// Project uses xUnit test classes rather than SpecFlow bindings; these are implementation skeletons.

using System;
using System.Threading.Tasks;

namespace PetSalon.SA.StepDefinitions;

public sealed class ShopSignaturePdfSteps
{
    // TODO: filesystem fixture rooted in a unique temporary app-data directory
    // TODO: renderer fixture using contract.hbs and kaiu.ttf from Infrastructure output
    // TODO: ViewModel fixture using FakeDialogService and a fake file opener

    public Task SignaturePadOutputIsTransparentCroppedPngAsync()
        => throw new NotImplementedException();

    public Task PngAndJpegImportsAreReencodedAsync(string format)
        => throw new NotImplementedException();

    public Task InvalidImagesLeaveNoProfileOrFilesAsync(string invalidType)
        => throw new NotImplementedException();

    public Task ProfileAndPngAreSavedAtomicallyAsync()
        => throw new NotImplementedException();

    public Task SettingDefaultLeavesExactlyOneDefaultAsync()
        => throw new NotImplementedException();

    public Task DeletingDefaultDoesNotGuessReplacementAsync()
        => throw new NotImplementedException();

    public Task PreviewDialogLoadsProfilesAndDefaultAsync()
        => throw new NotImplementedException();

    public Task SwitchingProfileRegeneratesPreviewWithNewSnapshotAsync()
        => throw new NotImplementedException();

    public void RendererPlacesShopSignatureOnlyInShopPositions()
        => throw new NotImplementedException();

    public Task CommitUsesSameBytesAsLatestPreviewAsync()
        => throw new NotImplementedException();

    public Task MissingSelectionKeepsAllSignatureLinesBlankAsync()
        => throw new NotImplementedException();

    public Task UnreadableSignatureWarnsAndFallsBackToBlankAsync(string failureType)
        => throw new NotImplementedException();

    public Task BackupContainsSignatureMetadataAndPngFilesAsync()
        => throw new NotImplementedException();

    public Task RestoreRejectsSignaturePathTraversalAsync()
        => throw new NotImplementedException();
}
