# language: zh-TW
# Generated by sa-expert
# Source: pm/customer-self-service-round2.feature
# Project: WPF MVVM（無 HTTP Controller / Route）
# Technical flow: CustomerFormView → CustomerFormViewModel → CustomerRegistrationService（planned）→ IPetSalonDbContext → SQLite

Feature: 顧客自填資料第二輪技術規格
  對應 View：src/PetSalon.Wpf/Views/CustomerFormView.xaml
  對應 ViewModel：src/PetSalon.Wpf/ViewModels/CustomerFormViewModel.cs
  對應既有 Entity：Owner → owners、Pet → pets
  對應既有欄位：Owner.Note、Pet.Note、Pet.ChipNumber、Pet.UnregisteredIdMethod、Pet.MedicalHistory、Pet.MedicalHistoryOther
  預計新增應用服務：CustomerRegistrationService
  交易界線：同一 scoped IPetSalonDbContext 內組合 Owner 與 Pets，只呼叫一次 SaveChangesAsync

  Background:
    Given 使用 SQLite in-memory 建立 PetSalonDbContext 並執行 EnsureCreated
    And DI 已註冊 IPetSalonDbContext、IClock、IIdGenerator 與 CustomerRegistrationService
    And CustomerFormViewModel 使用同一個 CustomerRegistrationService 處理整批送出

  Scenario: Owner.Note 與 Pet.Note 應在同一批建檔中保存
    Given CustomerRegistrationInput.Owner.Note 為「請先電話聯絡」
    And 第一筆 CustomerPetInput.Name 為「毛毛」且 Note 為「對吹風機敏感」
    When 呼叫 CustomerRegistrationService.CreateAsync 並允許建立
    Then owners 應新增一筆資料且 note 為「請先電話聯絡」
    And pets 應新增一筆 OwnerId 指向該 Owner 的資料
    And 該 pets.note 應為「對吹風機敏感」

  Scenario: CustomerFormView 應同時提供飼主與寵物備註控制項
    Given CustomerFormViewModel 已載入
    When 檢查 CustomerFormView 的 UI Automation tree
    Then 應存在 AutomationId「txt-customer-owner-note」
    And 每個寵物項目應存在可繫結 CustomerPetEntry.Note 的備註 TextBox
    And 兩個 TextBox 的 MaxLength 應為 1000

  Scenario: 病史應映射至 Pet.MedicalHistory 與 MedicalHistoryOther
    Given CustomerPetEntry 已選取「心臟病」與「氣喘」
    And MedicalHistoryOther 為空字串
    When CustomerFormViewModel 建立 CustomerPetInput
    Then CustomerPetInput.MedicalHistory 應等於 [「心臟病」,「氣喘」]
    And 建檔後 Pet.MedicalHistory 應保持相同內容

  Scenario: CustomerPetEntry 的以上皆無應與其他病史互斥
    Given CustomerPetEntry.MedicalHistory 中「心臟病」已選取
    When 將「以上皆無」設為選取
    Then CustomerPetEntry.MedicalHistory 只有「以上皆無」保持選取
    When 再將「其它」設為選取
    Then 「以上皆無」應取消選取
    And 「其它」應保持選取

  Scenario: 其它病史文字應保存
    Given CustomerPetEntry 已選取「其它」
    And MedicalHistoryOther 為「食物過敏」
    When 呼叫 CustomerRegistrationService.CreateAsync
    Then pets.medical_history JSON 應包含「其它」
    And pets.medical_history_other 應為「食物過敏」

  Scenario Outline: 晶片三態應映射至既有 Pet 欄位
    Given CustomerPetInput.ChipStatus 為「<晶片狀態>」
    And CustomerPetInput.ChipData 為「<晶片資料>」
    When CustomerRegistrationService 正規化晶片資料
    Then Pet.ChipNumber 應為「<預期晶片號碼>」
    And Pet.UnregisteredIdMethod 應為「<預期識別方式>」

    Examples:
      | 晶片狀態 | 晶片資料      | 預期晶片號碼  | 預期識別方式 |
      | 未填     |               | null          | null         |
      | 有       | 9001234567890 | 9001234567890 | null         |
      | 無       | 項圈牌 A12    | null          | 項圈牌 A12   |
      | 無       |               | null          | 無           |

  Scenario: 有晶片但號碼空白時應在寫入前驗證失敗
    Given CustomerRegistrationInput 含一筆 ChipStatus 為「有」且 ChipData 空白的 CustomerPetInput
    When 呼叫 CustomerRegistrationService.CreateAsync
    Then 應拋出 Code 為 VALIDATION_ERROR 的 AppException
    And ErrorMessage 應包含「晶片號碼為必填」
    And owners 與 pets 的筆數都不應增加

  Scenario: 第二隻寵物驗證失敗時不留下 Owner 或第一隻 Pet
    Given CustomerRegistrationInput.Owner 通過 OwnerService 既有必要欄位規則
    And 第一筆 CustomerPetInput 通過 PetService 既有規則
    And 第二筆 CustomerPetInput 缺少 Breed
    When 呼叫 CustomerRegistrationService.CreateAsync
    Then 應在呼叫 IPetSalonDbContext.SaveChangesAsync 前完成全部驗證
    And owners 與 pets 的筆數都不應增加

  Scenario Outline: 身分證或電話重複時回報可能重複
    Given owners 已存在 NationalId「A123456789」與 Phone「0912345678」的 Owner
    And 新輸入的「<比對欄位>」與既有 Owner 完全相同
    When 呼叫 CustomerRegistrationService.CheckDuplicateAsync
    Then 結果應標示 HasPotentialDuplicate 為 true
    And 應回傳相符 Owner 的 OwnerId、Name、NationalId 與 Phone 供警告顯示

    Examples:
      | 比對欄位   |
      | NationalId |
      | Phone      |

  Scenario: 店家取消可能重複建檔時保留 ViewModel 輸入
    Given CustomerFormViewModel 的重複檢查結果為 true
    And IDialogService.Confirm 回傳 false
    When 執行 SubmitCommand
    Then 不應呼叫 CustomerRegistrationService.CreateAsync
    And OwnerFormFields 與 CustomerPetEntry 不應 Reset

  Scenario: 店家允許可能重複建檔時仍使用單次 SaveChanges
    Given CustomerFormViewModel 的重複檢查結果為 true
    And IDialogService.Confirm 回傳 true
    When 執行 SubmitCommand
    Then CustomerRegistrationService.CreateAsync 應以 AllowDuplicate=true 執行
    And 同一個 IPetSalonDbContext 應只呼叫一次 SaveChangesAsync
    And owners 新增一筆且 pets 新增預期筆數

  Scenario: SubmitCommand 執行中不可啟動第二次建檔
    Given CustomerFormViewModel.IsBusy 為 true
    When 再次嘗試執行 SubmitCommand
    Then CustomerRegistrationService 不應收到第二次 CreateAsync 呼叫
    And btn-customer-submit 應為停用狀態
