# language: zh-TW
# Generated by sa-expert
# Source: pm/feedback-r5-signature-lines-blank.feature
# Project scan date: 2026-05-16
# Module type: PDF 模板簽名線變數移除
# Architecture: ContractTemplateRenderer → contract.hbs（第 239 / 240 / 432 行 owner.name 變數移除）

Feature: R5 簽名欄不得自動帶入姓名（含 Q2 乙方亦空白）
  對應模板：contract.hbs（src/PetSalon.Infrastructure/Pdf/Templates/contract.hbs）
  目標修改：
    - 第 239 行 `甲方簽章：<span class="blank wide">{{owner.name}}</span>` → `甲方簽章：<span class="blank wide"></span>`
    - 第 240 行 `乙方簽章：<span class="blank wide">貳寶寵物美容工坊</span>` → `乙方簽章：<span class="blank wide"></span>`（Q2 業主決議）
    - 第 432 行 `飼主簽名：<span class="blank wide">{{owner.name}}</span>` → `飼主簽名：<span class="blank wide"></span>`
    - 第 433 行 `美容人員簽名：<span class="blank wide"></span>` → 維持空白
  保留：4 個 .blank.wide 線條樣式（min-width 50mm）、簽名日期（rocYear/Month/Day 仍由系統帶入今日）

  Background:
    Given ContractTemplateRenderer 已透過 DI 註冊
    And contract.hbs 已套用 R5 修改（移除 3 處 owner.name 與 1 處「貳寶寵物美容工坊」）

  # ===== 技術層級（Core.Tests） =====

  Scenario: 新 page 4（原 page 3）甲方簽章線不得帶入 Owner.Name
    Given 已建立 ContractRenderData，Owner.Name="王小明"
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中對應第 238–240 行區塊（甲方簽章）之 <span class="blank wide"> 不應包含 "王小明"
    And 該 <span class="blank wide"> 之內容應為空白或僅空白字元
    And 該 <span> 之 class 應仍為 "blank wide"

  Scenario: 新 page 4（原 page 3）乙方簽章線不得帶入店家名稱
    Given 已建立 ContractRenderData
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中對應第 240 行「乙方簽章」之 <span class="blank wide"> 不應包含 "貳寶寵物美容工坊"
    And 該 <span class="blank wide"> 之內容應為空白
    And 該 <span> 之 class 應仍為 "blank wide"

  Scenario: 新 page 1（原 page 4）飼主簽名線不得帶入 Owner.Name
    Given 已建立 ContractRenderData，Owner.Name="王小明"
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中對應第 432 行「飼主簽名」之 <span class="blank wide"> 不應包含 "王小明"
    And 該 <span class="blank wide"> 之內容應為空白

  Scenario: 新 page 1 美容人員簽名線維持空白
    Given 已建立 ContractRenderData
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中對應第 433 行「美容人員簽名」之 <span class="blank wide"> 應為空白
    And 該 <span> 不應出現任何 Handlebars 樣板殘留字串如 "{{"

  Scenario: contract.hbs 原始檔第 239 行不應包含 {{owner.name}}
    When 讀取 contract.hbs 原始檔
    Then 第 239 行（甲方簽章）應不包含字串 "{{owner.name}}"
    And 第 239 行之 <span class="blank wide"> 應為空內容

  Scenario: contract.hbs 原始檔第 240 行（乙方簽章）不應包含「貳寶寵物美容工坊」字樣
    When 讀取 contract.hbs 原始檔
    Then 第 240 行應不包含字串 "貳寶寵物美容工坊"
    And 第 240 行之 <span class="blank wide"> 應為空內容

  Scenario: contract.hbs 原始檔第 432 行不應包含 {{owner.name}}
    When 讀取 contract.hbs 原始檔
    Then 第 432 行（飼主簽名）應不包含字串 "{{owner.name}}"
    And 第 432 行之 <span class="blank wide"> 應為空內容

  Scenario: 4 個簽名線之 CSS .blank.wide 維持 min-width 50mm
    When 讀取 contract.hbs 原始檔
    Then CSS 規則應包含 ".blank.wide { min-width: 50mm; }"
    And 4 個簽名線之 class 應為 "blank wide"

  Scenario: 簽名日期維持系統帶入今日民國年月日（本次不變更）
    Given 系統時鐘為 2026-05-16
    And 已建立 ContractRenderData，GroomingRecord.ServiceDate=2026-05-16
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中應出現 "中華民國" 字串
    And HTML 中對應之 rocYear 應顯示 "115"（民國 2026-1911=115）
    And HTML 中對應之 rocMonth 應顯示 "5"
    And HTML 中對應之 rocDay 應顯示 "16"

  Scenario Outline: 不同飼主姓名下 4 個簽名線皆為空白
    Given 已建立 ContractRenderData，Owner.Name="<飼主姓名>"
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中「甲方簽章」<span class="blank wide"> 不應出現 "<飼主姓名>"
    And HTML 中「乙方簽章」<span class="blank wide"> 應為空白
    And HTML 中「飼主簽名」<span class="blank wide"> 不應出現 "<飼主姓名>"
    And HTML 中「美容人員簽名」<span class="blank wide"> 應為空白

    Examples:
      | 飼主姓名 |
      | 王小明   |
      | 林大華   |
      | 陳美麗   |
