# language: zh-TW
# Generated by sa-expert
# Source: pm/feedback-r2-remove-system-signature-pad.feature
# Project scan date: 2026-05-16
# Module type: WPF MVVM + PuppeteerSharp PDF
# Architecture: ContractGenerateDialogViewModel / GroomingPageViewModel → ContractService → PuppeteerSharpContractGenerator

Feature: R2 移除系統內手寫簽名要求
  對應 Service：ContractService（src/PetSalon.Core/Services/ContractService.cs）
  對應 ViewModel：ContractGenerateDialogViewModel、GroomingPageViewModel
  對應 PDF 產生器：PuppeteerSharpContractGenerator（src/PetSalon.Infrastructure/Pdf/PuppeteerSharpContractGenerator.cs）
  對應 Render 介面：ContractRenderData.OwnerSignaturePng : byte[]（src/PetSalon.Core/Abstractions/IPdfGenerator.cs）
  模板片段：contract.hbs 第 238–241 行（甲方/乙方簽章）、第 427–434 行（飼主簽名 / 美容人員簽名）
  目標：完全移除系統內手寫簽名步驟，PDF 模板簽名線維持空白可供紙本親簽

  Background:
    Given SQLite 資料庫已套用最新 EF Core migration
    And owners / pets / grooming_records 三張表中已存在範例資料：飼主 "王小明"、寵物 "小白"、對應之 GroomingRecord
    And ContractGenerateDialogViewModel 與 GroomingPageViewModel 已透過 DI 註冊

  # ===== 技術層級（Core.Tests） =====

  Scenario: ContractService.GenerateAsync 不應因為 OwnerSignaturePng 為 byte[0] 而拋例外或阻擋
    Given 已建立 ContractRenderData，其中 OwnerSignaturePng = Array.Empty<byte>()
    When 呼叫 PuppeteerSharpContractGenerator.GenerateContractAsync(data, outputDir, 1)
    Then 不應擲出 "請先完成飼主簽名" 之例外
    And 應成功產出 PDF 檔（magic header %PDF）

  Scenario: ContractTemplateRenderer 對空簽名 byte[] 渲染後 HTML 不應出現 data:image/png;base64
    Given 已建立 ContractRenderData，OwnerSignaturePng = Array.Empty<byte>()
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中不應出現任何 "data:image/png;base64," 開頭之 img 嵌入
    And HTML 中之 4 個簽名線（甲方簽章 / 乙方簽章 / 飼主簽名 / 美容人員簽名）仍以 <span class="blank wide"> 呈現
    And HTML 中 4 個簽名線之內容皆為空字串

  Scenario: ContractTemplateRenderer 對任意 OwnerSignaturePng byte[] 都不應將簽名圖嵌入 4 個簽名線位置
    Given 已建立 ContractRenderData，OwnerSignaturePng = new byte[] { 0x89, 0x50, 0x4E, 0x47, ...(完整 PNG bytes) }
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中之「甲方簽章」span（contract.hbs 第 239 行）不應包含 <img> 或 base64 字串
    And HTML 中之「乙方簽章」span（第 240 行）不應包含 <img>
    And HTML 中之「飼主簽名」span（第 432 行）不應包含 <img>
    And HTML 中之「美容人員簽名」span（第 433 行）不應包含 <img>

  Scenario: 既有 GroomingRecord 之 Json 殘留簽名 Base64 欄位重新產 PDF 時不應寫入新值
    Given 已存在一筆 GroomingRecord，其 ContractPaths 已含一個 ContractVersion
    And 假設舊版資料中含一個 "OwnerSignatureBase64" 殘留欄位（不在 entity 定義中，由 JSON deserialize 忽略）
    When 呼叫 ContractService.GenerateAsync 對該 GroomingRecord 再產生一版 PDF
    Then 該 GroomingRecord 不應因此寫入新的簽名 Base64 欄位
    And 既有殘留欄位內容不應被主動清理或修改

  Scenario: GenerateContract 流程不再以「系統內飼主簽名」為前置條件
    Given GroomingPageViewModel.CanGenerateContract 不再檢查任何 OwnerSignaturePng 是否非空
    When 在沒有任何系統內簽名圖像的情況下呼叫 GroomingPageViewModel.GenerateContractCommand.Execute(null)
    Then ContractService.GenerateAsync 應被呼叫
    And PuppeteerSharpContractGenerator 應產出 PDF 檔
    And 不應出現「請先完成飼主簽名」之阻擋邏輯（如 throw InvalidOperationException 或 MessageBox）

  # ===== UI 層級（Wpf.UiTests） =====

  @ui
  Scenario: 服務紀錄 / 契約產生頁不應出現飼主簽名畫布
    Given 使用者已啟動 PetSalon.Wpf.exe 並導覽至服務紀錄頁（nav-grooming，待 dev 確認 AutomationId）
    When 使用者開啟 ContractGenerateDialog（btn-generate-contract）
    Then 對話框內不應存在 AutomationId 為 "canvas-owner-signature" 之控制項
    And 對話框內不應存在 AutomationId 為 "btn-clear-owner-signature" 之按鈕
    And 對話框內不應存在 AutomationId 為 "btn-confirm-owner-signature" 之按鈕

  @ui
  Scenario: 服務紀錄 / 契約產生頁不應出現店家簽名畫布
    Given 使用者已開啟 ContractGenerateDialog
    Then 對話框內不應存在 AutomationId 為 "canvas-shop-signature" 之控制項
    And 對話框內不應存在 AutomationId 為 "btn-clear-shop-signature" 之按鈕
    And 對話框內不應存在 AutomationId 為 "btn-confirm-shop-signature" 之按鈕

  @ui
  Scenario: 不需任何簽名步驟即可點擊 btn-generate-contract 並產生 PDF
    Given 使用者已開啟 ContractGenerateDialog 對應某筆 GroomingRecord
    When 使用者直接點擊 btn-generate-contract 按鈕（未經任何畫布簽名步驟）
    Then 對話框不應彈出「請先完成飼主簽名」或「請先完成店家簽名」之 MessageDialog
    And 應於約定的輸出資料夾下出現一個 .pdf 檔
    And 對話框應顯示「契約已產生」之成功訊息（待 dev 確認 AutomationId）
