# language: zh-TW
# Generated by sa-expert
# Source: pm/feedback-r6-physical-exam-abnormal-with-note.feature
# Project scan date: 2026-05-16
# Module type: WPF MVVM + EF Core Owned Entity 擴充 + Handlebars PDF
# Architecture: PetEditView / GroomingPageView → PetEditViewModel / GroomingPageViewModel → PetService / GroomingRecordService → PetSalonDbContext → SQLite
#               ContractTemplateRenderer → contract.hbs（第 334–363 行，每部位新增「異常」勾選格 + Note 顯示區）

Feature: R6 身體狀態檢視「異常」狀態必須寫入 PDF（含 Q5 異常說明、Q7 30 字截斷、Q8 皮毛規則、Q9 不同步回寫）
  對應 Entity：PhysicalExamination（src/PetSalon.Core/Entities/Pet.cs 第 31–39 行，**本次新增 6 個 *Note : string?**）
  對應 EF Configuration：PetConfiguration（OwnsOne，新增 phys_*_note 6 個 column）、GroomingRecordConfiguration（同步擴充）
  對應 Constants：BodyConditionOptions.Fur 需擴充為 { "正常", "異常", "打結", "跳蚤壁蝨" }
  對應 ViewModel：PetEditViewModel、GroomingPageViewModel（單選改 "正常"/"異常"、動態顯示 NoteTextBox）
  對應 View：PetEditView.xaml 第 99–123 行（6 個 ComboBox）+ 待 dev 新增 6 個動態 TextBox
  對應模板修改：contract.hbs 第 334、340、345、350、355、360 行（每行從只渲染「正常」改為同時渲染「正常」「異常」與選擇性 Note）

  Background:
    Given SQLite 資料庫已套用 R6 對應之 EF Core migration（AddPhysicalExaminationNotes）
    And pets、grooming_records 兩張表皆新增 phys_eyes_note / phys_ears_note / phys_teeth_note / phys_limbs_note / phys_skin_note / phys_fur_note 6 個 nullable TEXT column
    And Pet "小白" 之 PhysicalExamination 6 個欄位初始皆為 "正常"，6 個 *Note 皆為 null
    And ContractTemplateRenderer、PuppeteerSharpContractGenerator 已透過 DI 註冊

  # ===== 技術層級 / 模板渲染 =====

  Scenario: HTML 中 5 個部位（眼睛、耳朵、牙齒、四肢、皮膚）皆同時呈現「正常」與「異常」兩個勾選格
    Given 已建立合法 ContractRenderData，GroomingRecord.PhysicalExamination.Eyes="正常"
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中「1.眼睛」列應同時包含「正常」與「異常」兩個 <span class="cb"> 元素
    And HTML 中「2.耳朵」列應同時包含「正常」與「異常」兩個 <span class="cb"> 元素
    And HTML 中「3.牙齒」列應同時包含「正常」與「異常」兩個 <span class="cb"> 元素
    And HTML 中「4.四肢」列應同時包含「正常」與「異常」兩個 <span class="cb"> 元素
    And HTML 中「5.皮膚」列應同時包含「正常」與「異常」兩個 <span class="cb"> 元素

  Scenario: HTML 中「6.皮毛」列同時呈現「正常」「異常」「打結」「跳蚤壁蝨」四個勾選格
    Given 已建立合法 ContractRenderData
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中「6.皮毛」列應包含 4 個 <span class="cb"> 元素，依序對應 "正常"、"異常"、"打結"、"跳蚤壁蝨"

  Scenario: 部位為「正常」時僅勾選正常
    Given GroomingRecord.PhysicalExamination.Eyes="正常"
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中「1.眼睛」列之「正常」<span class="cb"> 應包含 class "on"
    And HTML 中「1.眼睛」列之「異常」<span class="cb"> 應**不**包含 class "on"

  Scenario: 部位為「異常」時僅勾選異常
    Given GroomingRecord.PhysicalExamination.Eyes="異常"
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中「1.眼睛」列之「正常」<span class="cb"> 應**不**包含 class "on"
    And HTML 中「1.眼睛」列之「異常」<span class="cb"> 應包含 class "on"

  Scenario: 部位欄位為 null / 空字串時兩格皆不勾選（理論上不應發生之邊界）
    Given GroomingRecord.PhysicalExamination.Eyes=null
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中「1.眼睛」列之「正常」與「異常」<span class="cb"> 皆**不**應包含 class "on"

  Scenario: 皮毛同時包含「異常」+「打結」之多選情境
    Given GroomingRecord.PhysicalExamination.Fur 包含 "異常" 與 "打結"
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中「6.皮毛」列之「異常」<span class="cb"> 應包含 class "on"
    And HTML 中「6.皮毛」列之「打結」<span class="cb"> 應包含 class "on"
    And HTML 中「6.皮毛」列之「正常」<span class="cb"> 應**不**包含 class "on"

  # ===== Q5：異常說明 Note 欄位 =====

  Scenario: PhysicalExamination 之屬性應包含 6 個 *Note : string?
    When 透過 reflection 檢查 typeof(PhysicalExamination).GetProperties()
    Then 應存在屬性 "EyesNote"，型別為 string?
    And 應存在屬性 "EarsNote"，型別為 string?
    And 應存在屬性 "TeethNote"，型別為 string?
    And 應存在屬性 "LimbsNote"，型別為 string?
    And 應存在屬性 "SkinNote"，型別為 string?
    And 應存在屬性 "FurNote"，型別為 string?

  Scenario: SQLite pets 與 grooming_records 表皆含 phys_*_note 6 個 column
    Given EF Core migration "AddPhysicalExaminationNotes" 已套用
    When 透過 PetSalonDbContext.Database.GetDbConnection() 查詢 SQLite schema
    Then pets table 應包含 column "phys_eyes_note"、"phys_ears_note"、"phys_teeth_note"、"phys_limbs_note"、"phys_skin_note"、"phys_fur_note"，型別均為 TEXT、NULL 允許
    And grooming_records table 應包含同樣 6 個 column

  Scenario: 異常 + Note 有值時 HTML 顯示說明文字
    Given GroomingRecord.PhysicalExamination.Eyes="異常" 且 EyesNote="結膜發紅，建議就醫"
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中「1.眼睛」列之「異常」<span class="cb"> 應包含 class "on"
    And HTML 中「1.眼睛」列旁或下方應顯示文字 "結膜發紅，建議就醫"

  Scenario: 異常但 Note 為 null 時 HTML 不顯示說明文字區
    Given GroomingRecord.PhysicalExamination.Eyes="異常" 且 EyesNote=null
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中「1.眼睛」列之「異常」<span class="cb"> 應包含 class "on"
    And HTML 中「1.眼睛」列不應出現額外的 Note 顯示區塊（如多餘的 <span> 或文字）

  Scenario: 正常但 Note 殘留資料時 HTML 不顯示說明文字區
    Given GroomingRecord.PhysicalExamination.Eyes="正常" 且 EyesNote="舊資料"
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中「1.眼睛」列之「正常」<span class="cb"> 應包含 class "on"
    And HTML 中「1.眼睛」列不應出現文字 "舊資料"

  Scenario: 既有 data/*.json 不含 *Note 欄位時 EF / JSON 反序列化視為 null
    Given 既有資料中某 Pet 之 SQLite 紀錄 phys_eyes_note column 為 NULL
    When 透過 PetSalonDbContext.Pets.Find(petId) 載入該 Pet
    Then 該 Pet.PhysicalExamination.EyesNote 應為 null
    And 後續 ContractTemplateRenderer 渲染 HTML 不應出現該 Note 顯示區

  Scenario Outline: 6 個部位之異常 + Note 行為一致
    Given GroomingRecord.PhysicalExamination.<部位>="<狀態>"
    And GroomingRecord.PhysicalExamination.<部位>Note="<說明>"
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中「<列名>」列之「<勾選格>」<span class="cb"> 應包含 class "on"
    And HTML 中「<列名>」列應顯示文字 "<PDF說明>"（若 PDF說明 為空則不顯示）

    Examples:
      | 部位  | 列名    | 狀態 | 說明           | 勾選格 | PDF說明        |
      | Eyes  | 1.眼睛  | 正常 |                | 正常   |                |
      | Eyes  | 1.眼睛  | 異常 | 結膜發紅       | 異常   | 結膜發紅       |
      | Ears  | 2.耳朵  | 異常 | 右耳有異味     | 異常   | 右耳有異味     |
      | Teeth | 3.牙齒  | 異常 | 牙結石嚴重     | 異常   | 牙結石嚴重     |
      | Limbs | 4.四肢  | 異常 | 左後腳跛行     | 異常   | 左後腳跛行     |
      | Skin  | 5.皮膚  | 異常 | 腹部紅疹       | 異常   | 腹部紅疹       |
      | Fur   | 6.皮毛  | 異常 | 大面積脫毛     | 異常   | 大面積脫毛     |

  # ===== Q7：30 字截斷 =====

  Scenario: PetService 寫入超過 30 字之 EyesNote 時應截斷至前 30 字
    Given 已建立 Pet 實例，PhysicalExamination.Eyes="異常"，EyesNote 為長度 45 字之字串 "結膜嚴重發紅伴隨黃色分泌物建議盡速就醫進行裂隙燈檢查與細菌培養"
    When 呼叫 PetService.SaveAsync(pet)
    Then 不應擲出阻擋例外
    And SQLite pets table 中 phys_eyes_note column 之值應為前 30 字 "結膜嚴重發紅伴隨黃色分泌物建議盡速就醫進行裂隙燈檢查與細"
    And 字串長度（以 Unicode codepoint 計）應為 30

  Scenario: PDF 渲染超過 30 字之 Note 時最多顯示前 30 字
    Given GroomingRecord.PhysicalExamination.EyesNote 為 45 字之字串
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中「1.眼睛」列之 Note 顯示區應最多包含前 30 字
    And 不應自動折行至第 2 行

  # ===== Q8：皮毛 Note 規則 =====

  Scenario: 皮毛只含「打結」未含「異常」時 HTML 不渲染 FurNote
    Given GroomingRecord.PhysicalExamination.Fur 包含 "打結" 但**不**包含 "異常"
    And FurNote="舊資料"
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中「6.皮毛」列之「打結」<span class="cb"> 應包含 class "on"
    And HTML 中「6.皮毛」列不應顯示文字 "舊資料"

  Scenario: 皮毛含「異常」且 FurNote 有值時 HTML 渲染 FurNote
    Given GroomingRecord.PhysicalExamination.Fur 包含 "異常"
    And FurNote="大面積脫毛"
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中「6.皮毛」列之「異常」<span class="cb"> 應包含 class "on"
    And HTML 中「6.皮毛」列應顯示文字 "大面積脫毛"

  # ===== Q9：服務當下異常不同步回寫 Pet =====

  Scenario: GroomingRecordService.SaveAsync 不應同步異動 Pet.PhysicalExamination
    Given Pet "小白" 之 PhysicalExamination.Eyes="正常" 且 EyesNote=null
    And 已建立新 GroomingRecord，其 PhysicalExamination.Eyes="異常" 且 EyesNote="結膜發紅"
    When 呼叫 GroomingRecordService.SaveAsync(groomingRecord)
    Then 該 GroomingRecord 寫入後其 PhysicalExamination.Eyes 應為 "異常"
    And 該 GroomingRecord 寫入後其 PhysicalExamination.EyesNote 應為 "結膜發紅"
    And 重新透過 PetService.GetByIdAsync("pet_小白_id") 載入 Pet 後，其 PhysicalExamination.Eyes 應**仍**為 "正常"
    And 該 Pet 之 PhysicalExamination.EyesNote 應**仍**為 null

  Scenario: 新建 GroomingRecord 之 PhysicalExamination 預設值來自 Pet 之當前狀態
    Given Pet "小白" 之 PhysicalExamination.Eyes="正常"
    When 透過 GroomingRecordService 為該 Pet 建立新 GroomingRecord（NewGroomingRecord(petId)）
    Then 新 GroomingRecord 之 PhysicalExamination.Eyes 預設應為 "正常"
    And 美容師可於 ViewModel 端獨立調整為 "異常" 而不影響 Pet 主檔

  # ===== UI 層級（Wpf.UiTests） =====

  @ui
  Scenario: PetEditView 將「眼睛」改選為「異常」時動態顯示 Note TextBox
    Given 使用者已啟動 PetSalon.Wpf.exe 並從 OwnerPageView 開啟 PetEditView
    And dev 已為 6 個身體部位 ComboBox 補上 AutomationId（cmb-phys-eyes / cmb-phys-ears / ...）
    When 使用者於 cmb-phys-eyes 選擇 "異常"
    Then 畫面應動態顯示 AutomationId "txt-phys-eyes-note" 之 TextBox
    And 該 TextBox 之 MaxLength 屬性應為 30

  @ui
  Scenario: 將「眼睛」從「異常」改回「正常」時 Note TextBox 隱藏並清空
    Given 使用者已將 cmb-phys-eyes 選為 "異常" 並在 txt-phys-eyes-note 輸入 "結膜發紅"
    When 使用者將 cmb-phys-eyes 改選為 "正常"
    Then txt-phys-eyes-note 應隱藏（Visibility = Collapsed）
    And 對應 PetEditViewModel.EyesNote 屬性應為 null 或空字串

  @ui
  Scenario: PetEditView 之 txt-phys-eyes-note 限制最多輸入 30 字元
    Given 使用者已將 cmb-phys-eyes 選為 "異常" 且 txt-phys-eyes-note 顯示中
    When 使用者嘗試貼上 45 字之文字
    Then txt-phys-eyes-note.Text 之長度應 ≤ 30
    And 對應之 ViewModel 屬性也應 ≤ 30 字

  @ui
  Scenario: 皮毛只勾「打結」未勾「異常」時 UI 不顯示 FurNote TextBox
    Given dev 已為皮毛之多選控制項補上 AutomationId（cb-fur-normal、cb-fur-abnormal、cb-fur-tangled、cb-fur-flea-tick）
    When 使用者只勾選 cb-fur-tangled 但未勾選 cb-fur-abnormal
    Then 畫面上不應顯示 AutomationId "txt-phys-fur-note" 之 TextBox

  @ui
  Scenario: 皮毛同時勾「異常」+「打結」時 UI 顯示 FurNote TextBox
    Given 使用者同時勾選 cb-fur-abnormal 與 cb-fur-tangled
    Then 畫面應顯示 AutomationId "txt-phys-fur-note" 之 TextBox
    And 使用者可於該 TextBox 輸入文字至 ViewModel.FurNote
