# language: zh-TW
# Generated by sa-expert
# Source: pm/feedback-r4-contract-pdf-page-order.feature
# Project scan date: 2026-05-16
# Module type: PDF 模板結構調整（純 contract.hbs 修改）
# Architecture: ContractTemplateRenderer → contract.hbs 4 個 <section class="page"> 重新排序

Feature: R4 契約 PDF 頁面順序調整：服務資料表移至第一頁
  對應模板：contract.hbs（src/PetSalon.Infrastructure/Pdf/Templates/contract.hbs）
  目前頁序：page 1 簽約注意事項 / 基本資料 → page 2 健康狀況風險告知 / 乙方責任 → page 3 契約解除 / 簽署人聲明 / 甲乙方簽章 → page 4 服務資料表
  目標頁序：page 1 服務資料表 → page 2 簽約注意事項 / 基本資料 → page 3 健康狀況風險告知 / 乙方責任 → page 4 契約解除 / 簽署人聲明 / 甲乙方簽章
  涉及檔案：僅 contract.hbs（4 個 <section class="page"> 之 DOM 順序重新排列）；CSS .page-break-after 規則不變
  本次測試使用 PdfPig 或 ContractTemplateRenderer 之 HTML 字串解析來推斷頁序

  Background:
    Given ContractTemplateRenderer、PuppeteerSharpContractGenerator 已透過 DI 註冊
    And contract.hbs 已套用 R4 調整（4 個 section 順序重排）
    And Chromium browser 已下載並快取於 chromiumCacheDir

  # ===== 技術層級（Core.Tests） =====

  Scenario: HTML 中 4 個 <section class="page"> 之出現順序符合新頁序
    Given 已建立合法 ContractRenderData
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中第 1 個 <section class="page"> 應包含「寵物美容契約書」標題（原 page 4 之 h1）
    And HTML 中第 1 個 section 應包含「服務項目」、「寵物身體狀態檢視」、「寵物病史」字串
    And HTML 中第 2 個 <section class="page"> 應包含「簽約注意事項」與「一、基本資料」字串
    And HTML 中第 3 個 <section class="page"> 應包含「四、乙方責任」與「五、甲方義務及責任」字串
    And HTML 中第 4 個 <section class="page"> 應包含「六、契約解除及終止之退費方式」、「七、其他事項」、「甲方簽章」、「乙方簽章」字串

  Scenario: PDF 第 1 頁應包含飼主基本資料表、服務項目、寵物個性、儲值金額、獸醫院、身體狀態、病史、條款、簽名區
    Given 已建立合法 ContractRenderData
    When 呼叫 PuppeteerSharpContractGenerator.GenerateContractAsync(data, outputDir, 1)
    Then 解析產出之 PDF 後，第 1 頁文字應包含 "服務項目"
    And 第 1 頁文字應包含 "寵物個性"
    And 第 1 頁文字應包含 "儲值金額"
    And 第 1 頁文字應包含 "獸醫院"
    And 第 1 頁文字應包含 "寵物身體狀態檢視"
    And 第 1 頁文字應包含 "寵物病史"
    And 第 1 頁文字應包含 "狀況良好"
    And 第 1 頁文字應包含 "飼主簽名"
    And 第 1 頁文字應包含 "美容人員簽名"

  Scenario: PDF 第 2 頁應包含原 page 1 內容
    Given 已建立合法 ContractRenderData
    When 呼叫 PuppeteerSharpContractGenerator.GenerateContractAsync(data, outputDir, 1)
    Then 解析後第 2 頁文字應包含 "簽約注意事項"
    And 第 2 頁文字應包含 "一、基本資料"
    And 第 2 頁文字應包含 "二、美容服務預約"
    And 第 2 頁文字應包含 "三、犬/貓健康狀況"

  Scenario: PDF 第 3 頁應包含原 page 2 內容
    Given 已建立合法 ContractRenderData
    When 呼叫 PuppeteerSharpContractGenerator.GenerateContractAsync(data, outputDir, 1)
    Then 解析後第 3 頁文字應包含 "四、乙方責任"
    And 第 3 頁文字應包含 "五、甲方義務及責任"
    And 第 3 頁文字可包含 "三、犬/貓健康狀況" 後段（健康狀況風險告知後段）

  Scenario: PDF 第 4 頁應包含原 page 3 內容
    Given 已建立合法 ContractRenderData
    When 呼叫 PuppeteerSharpContractGenerator.GenerateContractAsync(data, outputDir, 1)
    Then 解析後第 4 頁文字應包含 "六、契約解除及終止之退費方式"
    And 第 4 頁文字應包含 "七、其他事項"
    And 第 4 頁文字應包含 "簽署人已詳閱本契約全部條款"
    And 第 4 頁文字應包含 "甲方簽章"
    And 第 4 頁文字應包含 "乙方簽章"
    And 第 4 頁文字應包含 "簽署日期：中華民國"

  Scenario: PDF 總頁數應維持 4 頁
    Given 已建立合法 ContractRenderData
    When 呼叫 PuppeteerSharpContractGenerator.GenerateContractAsync(data, outputDir, 1)
    Then 產出之 PDF 之頁數應為 4
    And 不應為 3、5 或其他數量

  Scenario: CSS page-break-after 規則：前 3 個 section 強制分頁、最後一個維持 :last-child auto
    Given contract.hbs 已套用 R4 順序調整
    When 讀取 contract.hbs 原始檔內容
    Then CSS 規則應包含 ".page { page-break-after: always; }"
    And CSS 規則應包含 ".page:last-child { page-break-after: auto; }"
    And 4 個 <section class="page"> 中前 3 個於渲染時應觸發分頁、第 4 個應為頁末不再分頁

  Scenario: 本次不主動新增頁碼或頁眉
    Given 已建立合法 ContractRenderData
    When 呼叫 PuppeteerSharpContractGenerator.GenerateContractAsync(data, outputDir, 1)
    Then HTML 中不應出現 @page { @bottom-center } 之頁碼定義
    And HTML 中不應出現 @page { @top-* } 之頁眉定義
    And 產出之 PDF 每頁不應呈現 "Page 1 of 4" 或類似頁碼字串

  Scenario: 頁面搬移後不應造成版面異常（手動視覺檢查 + 啟發式斷言）
    Given 已建立合法 ContractRenderData
    When 呼叫 PuppeteerSharpContractGenerator.GenerateContractAsync(data, outputDir, 1)
    Then 產出之 PDF 大小應大於 5000 byte（確認 Chromium 確實有渲染內容）
    And PDF 之 magic header 前 4 byte 應為 0x25 0x50 0x44 0x46
    And 各頁之文字（透過 PDF 解析）不應出現 "Object reference not set" 或 "{{" 樣板殘留
    # 視覺跑版（表格截斷、文字重疊、跨頁殘行）需人工 review；建議產生範例 PDF 並由 QA 目視確認
