# language: zh-TW
# Generated by sa-expert
# Source: pm/feedback-r7-medical-history-none-of-above.feature
# Project scan date: 2026-05-16
# Module type: WPF MVVM + Constants 擴充 + Handlebars PDF
# Architecture: PetEditView / GroomingPageView → PetEditViewModel / GroomingPageViewModel（互斥規則）
#               ContractTemplateRenderer → contract.hbs（第 377–406 行新增「以上皆無」勾選格）

Feature: R7 寵物病史新增「以上皆無」選項（含 Q6 空陣列視為以上皆無）
  對應 Constants：MedicalHistoryOptions.All（src/PetSalon.Core/Constants/MedicalHistoryOptions.cs），由 18 項擴充為 19 項
  對應 Entity：Pet.MedicalHistory : List<string>、GroomingRecord.MedicalHistory : List<string>（皆無需 schema 變更）
  對應 ViewModel：PetEditViewModel、GroomingPageViewModel（負責互斥規則）
  對應 View：PetEditView.xaml 第 128–146 行（病史多選 ItemsControl）
  對應模板修改：contract.hbs 第 377–406 行（第 3 列末尾新增「以上皆無」<span class="cb">），並改寫渲染條件為 `MedicalHistory.Contains("以上皆無") || MedicalHistory.Length == 0`
  PDF 渲染來源：GroomingRecord.MedicalHistory（非 Pet.MedicalHistory）

  Background:
    Given ContractTemplateRenderer 已透過 DI 註冊
    And PetEditViewModel、GroomingPageViewModel 已透過 DI 註冊

  # ===== 技術層級 / Constants 與 Service =====

  Scenario: MedicalHistoryOptions.All 擴充為 19 項且「以上皆無」位於末尾
    When 透過 reflection 取得 MedicalHistoryOptions.All 之 Count
    Then Count 應為 19
    And MedicalHistoryOptions.All[18] 應為 "以上皆無"
    And MedicalHistoryOptions.All[0..17] 之 18 個字串應與原 18 項順序、字元逐字相同

  Scenario: MedicalHistoryOptions.IsValid("以上皆無") 應回傳 true
    When 呼叫 MedicalHistoryOptions.IsValid("以上皆無")
    Then 回傳值應為 true

  Scenario: 後端 PetService / GroomingRecordService 不對 MedicalHistory 內容組合執行額外驗證
    Given 已建立 Pet 實例，其 MedicalHistory = ["以上皆無", "心臟病"]（語意衝突但是合法字串）
    When 呼叫 PetService.SaveAsync(pet)
    Then 不應擲出例外
    And SQLite pets table 中該筆紀錄之 MedicalHistory JSON column 應為 ["以上皆無","心臟病"]
    # 互斥規則由 UI / ViewModel 端強制執行，Service 不阻擋

  # ===== 模板渲染 =====

  Scenario: PDF 寵物病史區塊新增「以上皆無」勾選格
    Given 已建立合法 ContractRenderData
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中「寵物病史」區塊應包含 <span class="cb"> 元素對應 "以上皆無"
    And 該勾選格應位於第 3 列末尾（與 "傳染性疾病"、"其它" 同列）

  Scenario: MedicalHistory 包含「以上皆無」時 HTML 勾選「以上皆無」
    Given GroomingRecord.MedicalHistory = ["以上皆無"]
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中「以上皆無」<span class="cb"> 應包含 class "on"
    And HTML 中其他 18 項病史 <span class="cb"> 皆**不**應包含 class "on"

  Scenario: MedicalHistory 為空陣列時 HTML 自動勾選「以上皆無」（Q6）
    Given GroomingRecord.MedicalHistory = []
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中「以上皆無」<span class="cb"> 應包含 class "on"
    And HTML 中其他 18 項病史 <span class="cb"> 皆**不**應包含 class "on"

  Scenario: MedicalHistory 包含具體病史時 HTML 不勾選「以上皆無」
    Given GroomingRecord.MedicalHistory = ["心臟病", "氣喘"]
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中「心臟病」<span class="cb"> 應包含 class "on"
    And HTML 中「氣喘」<span class="cb"> 應包含 class "on"
    And HTML 中「以上皆無」<span class="cb"> 應**不**包含 class "on"

  Scenario: 既有 SQLite 資料中 MedicalHistory = [] 之 Pet 不需 migration
    Given pets table 中某 Pet 之 MedicalHistory JSON column 值為 "[]"
    When 透過 PetSalonDbContext.Pets.Find(petId) 載入該 Pet
    Then 該 Pet.MedicalHistory 應為空 List<string>
    And 後續為該 Pet 產生 PDF 時 HTML 中「以上皆無」勾選格應自動勾選
    And SQLite 中該筆紀錄不應被自動異動

  Scenario Outline: 不同 MedicalHistory 輸入下 HTML 之「以上皆無」勾選行為
    Given GroomingRecord.MedicalHistory = <輸入>
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中「以上皆無」<span class="cb"> 是否包含 class "on" 應為 "<以上皆無勾選>"

    Examples:
      | 輸入                    | 以上皆無勾選 |
      | []                      | true         |
      | ["以上皆無"]            | true         |
      | ["心臟病"]              | false        |
      | ["其它"]                | false        |
      | ["心臟病", "氣喘"]      | false        |

  # ===== UI 層級（Wpf.UiTests） =====

  @ui
  Scenario: PetEditView 之「寵物病史」區塊應包含「以上皆無」CheckBox
    Given 使用者已啟動 PetSalon.Wpf.exe 並開啟 PetEditView
    And dev 已為「以上皆無」CheckBox 補上 AutomationId="cb-medical-none-of-above"
    Then 畫面應顯示 AutomationId "cb-medical-none-of-above" 之 CheckBox
    And 該 CheckBox 之 IsEnabled 應為 true

  @ui
  Scenario: 勾選「以上皆無」時 ViewModel 自動取消其他 18 項病史
    Given 使用者已勾選「心臟病」與「氣喘」（cb-medical-heart-disease、cb-medical-asthma）
    When 使用者勾選 cb-medical-none-of-above
    Then cb-medical-heart-disease 之 IsChecked 應為 false
    And cb-medical-asthma 之 IsChecked 應為 false
    And 對應 PetEditViewModel.MedicalHistory 之最終陣列應只包含 "以上皆無"

  @ui
  Scenario: 勾選任一具體病史時 ViewModel 自動取消「以上皆無」
    Given 使用者已勾選 cb-medical-none-of-above
    When 使用者勾選 cb-medical-heart-disease
    Then cb-medical-none-of-above 之 IsChecked 應為 false
    And 對應 ViewModel.MedicalHistory 之最終陣列應只包含 "心臟病"

  @ui
  Scenario: 「以上皆無」與「其它」互斥
    Given 使用者已勾選 cb-medical-none-of-above
    When 使用者勾選 cb-medical-other
    Then cb-medical-none-of-above 之 IsChecked 應為 false
    And 對應 ViewModel.MedicalHistory 之最終陣列應只包含 "其它"

  @ui
  Scenario: 取消所有具體病史後陣列回到 [] 且後續 PDF 仍勾選「以上皆無」
    Given 使用者已勾選 cb-medical-heart-disease 並儲存
    When 使用者取消 cb-medical-heart-disease 並再次儲存
    Then 對應 ViewModel.MedicalHistory 應為空 List<string>
    And SQLite pets table 中該筆紀錄之 MedicalHistory JSON column 應為 "[]"
    And 後續為該 Pet 產出之 PDF HTML 中「以上皆無」<span class="cb"> 應包含 class "on"
