# language: zh-TW
# Generated by sa-expert
# Source: pm/feedback-r8-contract-clauses-text.feature
# Project scan date: 2026-05-16
# Module type: PDF 模板純文字替換
# Architecture: ContractTemplateRenderer → contract.hbs（第 413–425 行 ＊段 + <ol> 全段替換為客戶原文，含 Q4 修正）

Feature: R8 PDF 條款短版文字改用客戶提供原文（含 Q4 修正：「視為飼主惡意棄養」）
  對應模板：contract.hbs（src/PetSalon.Infrastructure/Pdf/Templates/contract.hbs）
  目標修改：
    - 第 413–415 行 <p> ＊段：替換為客戶提供之 ＊段原文
    - 第 416–425 行 <ol> 7 點條款：擴充為 8 點，逐字替換為客戶原文（第 2 點含 Q4 修正：「為飼主惡意養」→「視為飼主惡意棄養」）
  位置：新 page 1（R4 重排序後即原 page 4）末尾
  注意：所有測試比對皆需用 string equality（Ordinal），保留全形標點、半形空格、底線字元
  ContractTemplateRenderer 使用 Handlebars.Net 且 TextEncoder=null（不做 HTML escape），中文字會原樣輸出

  Background:
    Given ContractTemplateRenderer 已透過 DI 註冊
    And contract.hbs 已套用 R8 修改

  # ===== 技術層級（Core.Tests，純字串斷言） =====

  Scenario: ＊段同意文字逐字符合客戶原文
    Given 已建立合法 ContractRenderData
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中應包含字串：
      """
      ＊以上資料由飼主本人提供，並同意將資料內容提供於公司存續期間以電話、簡訊和寄發DM方式，提供相關活動或促銷訊息、或帶寵物到動物醫院留存相關資料使用。
      """

  Scenario: 1~8 點條款數量應為 8 點
    Given 已建立合法 ContractRenderData
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中對應第 416–425 行區塊之 <ol> 應包含正好 8 個 <li> 元素
    And 不應為 7 個或其他數量

  Scenario: 條款第 1 點原文逐字符合
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中 <ol> 第 1 個 <li> 內容應為：
      """
      除本契約另有約定、特殊緊急情況、或不可抗力之情況外，未經飼主同意，店家不得將寵物帶離美容場所（同上店家地址）、轉售、轉讓或以其他變相方法作為其他用途。
      """

  Scenario: 條款第 2 點原文已修正為「視為飼主惡意棄養」（Q4）
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中 <ol> 第 2 個 <li> 內容應為：
      """
      飼主應於美容當日，將寵物領回，如經通知1日內未領回，依動保法第29條第一款通知主管機關，視為飼主惡意棄養，相關罰金為3萬~15萬元，其他衍生性費用將跟飼主求償，例：人員加班費等。
      """
    And HTML 中 <ol> 第 2 個 <li> 不應包含舊錯字 "為飼主惡意養"（缺「視」與「棄」之版本）
    And HTML 中 <ol> 第 2 個 <li> 應包含 "視為"
    And HTML 中 <ol> 第 2 個 <li> 應包含 "惡意棄養"

  Scenario: 條款第 3 點原文逐字符合
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中 <ol> 第 3 個 <li> 內容應為：
      """
      寵物發生攻擊行為，如因飼主未普盡告知義務而造成店內人員傷亡、財物毀損等費用，將全額向飼主（寵物占有權人）求償。
      """

  Scenario: 條款第 4 點原文逐字符合
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中 <ol> 第 4 個 <li> 內容應為：
      """
      店家應按本契約約定內容提供一定品質之美容服務。若因可歸責於店家或其受僱人之事由，導致其提供之美容服務有瑕疵，造成飼主發生損失的情況，飼主得要求減少價金或解除契約。
      """

  Scenario: 條款第 5 點原文逐字符合
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中 <ol> 第 5 個 <li> 內容應為：
      """
      本契約之任一方得隨時終止本契約，若因本契約之終止而生損害之一方得向他方請求賠償。
      """

  Scenario: 條款第 6 點原文逐字符合
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中 <ol> 第 6 個 <li> 內容應為：
      """
      於美容服務期間，如發現寵物有異常狀態，應立即通知飼主並妥善處理，如發生異常狀態的原因，可歸責店家之操作行為，店家應負損害賠償責任，例：摔傷寵物等。
      """

  Scenario: 條款第 7 點保留「以 地方法院」之半形空格
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中 <ol> 第 7 個 <li> 內容應為：
      """
      因本契約所生之訴訟，雙方合意以 地方法院為管轄法院。
      """
    And HTML 中 <ol> 第 7 個 <li> 之 "以" 與 "地方法院" 之間應保留正好 1 個半形空格 (ASCII 0x20)
    And 該空格不應被 HTML normalize 或被其他工具自動清除

  Scenario: 條款第 8 點以可手寫之長底線呈現
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中 <ol> 第 8 個 <li> 內容應以 "其他：" 開頭
    And HTML 中 <ol> 第 8 個 <li> 應包含可手寫之長底線（建議使用既有 .blank.xwide 樣式或重複的 _ 底線字元）

  Scenario: ＊段位置應位於 1~8 點條款之前
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中 "＊以上資料由飼主本人提供" 之出現位置應早於 <ol> 之出現位置
    And HTML 中 <ol> 之 8 個 <li> 順序應為 1, 2, 3, 4, 5, 6, 7, 8

  Scenario: contract.hbs 原始檔比對：第 413–415 行為 ＊段、第 416–425 行區段含 8 個 <li>
    When 讀取 contract.hbs 原始檔
    Then 第 413 行（或附近）應為包含 "＊以上資料由飼主本人提供" 之 <p>
    And 第 416–425 行之 <ol> 區段應包含 8 個 <li>
    And 第 2 個 <li> 應包含 "視為飼主惡意棄養"

  Scenario: 文字替換後不應出現亂碼、錯字、重複段落或截斷
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中 8 個 <li> 之文字皆不應出現 "????" 或 "&#" 開頭之亂碼實體
    And HTML 中不應出現連續 2 次以上完全相同之 <li> 內容
    And HTML 中不應出現原模板舊文字殘留如 "基本契約同付屬定"、"寵主進店美容契約書"、"店家得基於契約所涉可歸責甲方"

  Scenario Outline: 8 點條款逐點檢查包含關鍵字
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中 <ol> 第 "<點次>" 個 <li> 應包含關鍵字 "<關鍵字>"

    Examples:
      | 點次 | 關鍵字             |
      | 1    | 不得將寵物帶離     |
      | 2    | 視為飼主惡意棄養   |
      | 3    | 寵物占有權人       |
      | 4    | 一定品質之美容服務 |
      | 5    | 任一方得隨時終止   |
      | 6    | 摔傷寵物           |
      | 7    | 以 地方法院        |
      | 8    | 其他：             |
