# language: zh-TW
# Generated by sa-expert
# Source: pm/feedback-r3-chip-unregistered-not-inferred.feature
# Project scan date: 2026-05-16
# Module type: WPF MVVM + EF Core SQLite + Handlebars PDF
# Architecture: PetEditView → PetEditViewModel → PetService → PetSalonDbContext → SQLite
#               ContractTemplateRenderer → contract.hbs（修改第 100、307 行勾選判定）

Feature: R3 晶片號碼空白時不得自動勾選「未登記 / 無」
  對應 Entity 欄位：Pet.ChipNumber : string?、Pet.UnregisteredIdMethod : string?
  對應 EF Configuration：PetConfiguration（src/PetSalon.Infrastructure/Persistence/Configurations/PetConfiguration.cs 第 22–23 行）
  對應 ViewModel：PetEditViewModel（src/PetSalon.Wpf/ViewModels/PetEditViewModel.cs）
  對應 View：PetEditView.xaml（第 58–66 行：ChipNumber TextBox + UnregisteredIdMethod TextBox）
  對應模板修改：contract.hbs 第 100 行（page 1「若未登記」）、第 307 行（page 4「無」勾選格）
  渲染規則：勾選依據由 {{#unless pet.chipNumber}} 改為 {{#if pet.unregisteredIdMethod}}

  Background:
    Given SQLite 資料庫已套用最新 EF Core migration
    And pets table 中已存在 Pet "小白"，其 OwnerId 指向飼主 "王小明"
    And PetService、ContractTemplateRenderer、PuppeteerSharpContractGenerator 已透過 DI 註冊

  # ===== 技術層級（Core.Tests） =====

  Scenario: ChipNumber 與 UnregisteredIdMethod 皆為 null 時 HTML 兩處勾選格皆不勾選
    Given Pet "小白" 之 ChipNumber=null 且 UnregisteredIdMethod=null
    And 已建立 ContractRenderData 包含此 Pet
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中對應 contract.hbs 第 100 行之「若未登記」<span class="cb"> 應**不**包含 class "on"
    And HTML 中對應第 96 行之「晶片號碼」<td> 應為空白
    And HTML 中對應第 100 行之「身份識別方式」字串後應為空白（{{pet.unregisteredIdMethod}} 渲染為空）
    And HTML 中對應第 307 行之「無」<span class="cb"> 應**不**包含 class "on"

  Scenario: ChipNumber 為 null 但 UnregisteredIdMethod 有值時兩處勾選格皆勾選
    Given Pet "小白" 之 ChipNumber=null 且 UnregisteredIdMethod="項圈牌號 A12"
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中對應第 100 行之「若未登記」<span class="cb"> 應包含 class "on"
    And HTML 中對應第 100 行之文字應顯示 "項圈牌號 A12"
    And HTML 中對應第 307 行之「無」<span class="cb"> 應包含 class "on"

  Scenario: ChipNumber 有值且 UnregisteredIdMethod 為 null 時兩處勾選格皆不勾選
    Given Pet "小白" 之 ChipNumber="900123456789012" 且 UnregisteredIdMethod=null
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中對應第 96 行之「晶片號碼」<td> 應顯示 "900123456789012"
    And HTML 中對應第 100 行之「若未登記」<span class="cb"> 應**不**包含 class "on"
    And HTML 中對應第 307 行之「無」<span class="cb"> 應**不**包含 class "on"

  Scenario: ChipNumber 與 UnregisteredIdMethod 皆有值（罕見）以 UnregisteredIdMethod 為勾選依據
    Given Pet "小白" 之 ChipNumber="900123456789012" 且 UnregisteredIdMethod="舊晶片損壞，已換項圈牌號 B05"
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中「晶片號碼」<td> 應顯示 "900123456789012"
    And HTML 中第 100 行「若未登記」<span class="cb"> 應包含 class "on"
    And HTML 中第 100 行文字應顯示 "舊晶片損壞，已換項圈牌號 B05"
    And HTML 中第 307 行「無」<span class="cb"> 應包含 class "on"

  Scenario: 不新增任何專用布林欄位至 Pet entity
    When 透過 reflection 檢查 typeof(Pet).GetProperties()
    Then 不應存在屬性名為 "IsUnregistered" 之 bool / bool? 屬性
    And 應沿用既有 "ChipNumber : string?" 與 "UnregisteredIdMethod : string?" 兩個屬性
    And PetConfiguration 中不應出現對 "IsUnregistered" 欄位之 EF 設定

  Scenario: PetService.SaveAsync 不應對 ChipNumber 為 null 之 Pet 拋例外
    Given 已建立 Pet 實例，其 ChipNumber=null 且 UnregisteredIdMethod=null
    When 呼叫 PetService.SaveAsync(pet)
    Then 不應擲出任何例外
    And SQLite pets table 中該筆紀錄之 ChipNumber column 應為 NULL
    And UnregisteredIdMethod column 應為 NULL

  Scenario Outline: 不同晶片資料組合下 contract.hbs 兩處勾選格之 class 渲染
    Given Pet 之 ChipNumber="<晶片>"
    And Pet 之 UnregisteredIdMethod="<識別方式>"
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中第 100 行「若未登記」勾選格之 class 是否包含 "on" 應為 "<page1勾選>"
    And HTML 中第 307 行「無」勾選格之 class 是否包含 "on" 應為 "<page4勾選>"

    Examples:
      | 晶片            | 識別方式             | page1勾選 | page4勾選 |
      |                 |                      | false     | false     |
      |                 | 無                   | true      | true      |
      |                 | 項圈牌號 A12         | true      | true      |
      | 900123456789012 |                      | false     | false     |
      | 900123456789012 | 舊晶片損壞已換項圈   | true      | true      |

  # ===== UI 層級（Wpf.UiTests） =====

  @ui
  Scenario: PetEditView 顯示輔助文字提示無晶片填寫方式（需 dev 新增 AutomationId="txt-pet-chip-hint"）
    Given 使用者已啟動 PetSalon.Wpf.exe 並從 OwnerPageView 點擊 btn-add-pet 開啟 PetEditView
    When 使用者觀察「晶片號碼」欄位旁
    Then 應顯示 AutomationId "txt-pet-chip-hint" 之 TextBlock
    And 該 TextBlock 文字應包含「若無晶片」與「身份識別方式」字樣
    And 該 TextBlock 應提供範例「項圈牌號 A12」或「無」

  @ui
  Scenario: 使用者在 PetEditView 留空 ChipNumber 並填 UnregisteredIdMethod 後儲存
    Given 使用者已開啟 PetEditView（dev 階段補上 AutomationId："txt-pet-chip-number"、"txt-pet-unregistered-id"）
    When 使用者保留 txt-pet-chip-number 為空
    And 使用者在 txt-pet-unregistered-id 輸入 "項圈牌號 A12"
    And 使用者點擊 btn-save-pet（待 dev 確認 AutomationId）
    Then 重新讀取該 Pet 後，其 ChipNumber 應為 null 或空字串
    And 其 UnregisteredIdMethod 應為 "項圈牌號 A12"
