# language: zh-TW
# Generated by sa-expert
# Source: pm/feedback-r1-emergency-contact-optional.feature
# Project scan date: 2026-05-16
# Module type: WPF MVVM + EF Core SQLite + Handlebars/Puppeteer PDF
# Architecture: View(OwnerPageView) → OwnerPageViewModel → OwnerService → PetSalonDbContext → SQLite
#               ContractService → PuppeteerSharpContractGenerator → ContractTemplateRenderer → contract.hbs

Feature: R1 緊急聯絡人欄位取消必填
  對應 Entity：Owner（src/PetSalon.Core/Entities/Owner.cs）
  對應 ViewModel：OwnerPageViewModel（src/PetSalon.Wpf/ViewModels/OwnerPageViewModel.cs）
  對應 View：OwnerPageView.xaml（src/PetSalon.Wpf/Views/OwnerPageView.xaml）
  對應 Service：OwnerService（src/PetSalon.Core/Services/OwnerService.cs）
  對應模板片段：contract.hbs 第 122–126 行（page 1）、第 263–265 行（page 4 / 新 page 1 → R4 後）
  目標欄位：Owner.EmergencyContactName / EmergencyContactPhone / EmergencyContactRelationship

  Background:
    Given SQLite 資料庫已套用最新 EF Core migration
    And PetSalonDbContext 之 Owners DbSet 可讀寫
    And OwnerService 已透過 DI 註冊

  # ===== 技術層級（Core.Tests / 單元 + 整合） =====

  Scenario: OwnerService 對三欄全空之 Owner 寫入不應拋例外
    Given 已建立一個 Owner 實例：
      | 屬性                             | 值              |
      | Name                            | 王小明          |
      | NationalId                      | A123456789      |
      | Phone                           | 0912345678      |
      | Address                         | 桃園市桃園區慈文路322巷5號 |
      | EmergencyContactName            | "" (空字串)     |
      | EmergencyContactPhone           | "" (空字串)     |
      | EmergencyContactRelationship    | "" (空字串)     |
    When 呼叫 OwnerService.SaveAsync(owner)
    Then 不應擲出任何例外
    And SQLite owners table 中應存在一筆 Owner，OwnerId 為新產生之 id
    And 該筆紀錄之 EmergencyContactName 應為空字串
    And 該筆紀錄之 EmergencyContactPhone 應為空字串
    And 該筆紀錄之 EmergencyContactRelationship 應為空字串

  Scenario: OwnerService 對既有 Owner 清空三欄之 Update 不應拋例外
    Given SQLite owners table 中已存在 Owner "王小明"，其 EmergencyContactName="李四"、EmergencyContactPhone="0987654321"、EmergencyContactRelationship="配偶"
    When 將該 Owner 之 EmergencyContactName / Phone / Relationship 三欄皆設為空字串
    And 呼叫 OwnerService.SaveAsync(owner)
    Then 不應擲出任何例外
    And 該筆紀錄之三欄應更新為空字串

  Scenario: ContractTemplateRenderer 對三欄全空之 Owner 渲染後 HTML 不應包含 null / 未填寫 / "-" 佔位字串
    Given 已建立 ContractRenderData，其中 Owner.EmergencyContactName="" 且 Owner.EmergencyContactPhone="" 且 Owner.EmergencyContactRelationship=""
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then 回傳的 HTML 字串於「(二) 消費者/飼主」表「緊急聯絡人」儲存格不應出現 "null"
    And HTML 不應出現 "未填寫"
    And HTML 不應出現 "-" 佔位字串
    And HTML 不應出現 "{{owner.emergencyContactName}}" 等樣板殘留
    And HTML 中對應「緊急聯絡人」之 <td class="val"> 內容應為空白或僅含空白字元

  Scenario: ContractTemplateRenderer 當 EmergencyContactName 有值但 Relationship 為空時不輸出空括號
    Given 已建立 ContractRenderData，其中 Owner.EmergencyContactName="李大華" 且 Owner.EmergencyContactRelationship=""
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中「緊急聯絡人」儲存格應顯示 "李大華"
    And HTML 中「緊急聯絡人」儲存格不應出現 "()" 空括號
    And contract.hbs 第 123 行之 {{#if owner.emergencyContactRelationship}} 條件包覆應仍存在

  Scenario: 新 page 1（R4 重排序後，原 page 4）服務資料表三列空值
    Given 已建立 ContractRenderData，其中 Owner 之 EmergencyContact 三欄皆為空
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中新 page 1 之「緊急聯絡人」儲存格應為空白
    And HTML 中新 page 1 之「與飼主關係」儲存格應為空白
    And HTML 中新 page 1 之「緊急聯絡電話」儲存格應為空白
    And 上述儲存格皆不應包含 "null" 或 "未填寫" 字串

  Scenario: PuppeteerSharpContractGenerator.GenerateContractAsync 對三欄空之 Owner 應產生有效 PDF
    Given 已建立 ContractRenderData，Owner.EmergencyContactName="" 且其他 Emergency 欄位皆為空
    When 呼叫 PuppeteerSharpContractGenerator.GenerateContractAsync(data, outputDir, nextVersion: 1)
    Then 不應擲出任何例外
    And 回傳的 ContractGenerateOutput.AbsolutePath 應指向一個存在的 PDF 檔
    And PDF 檔之 magic header 前 4 byte 應為 0x25 0x50 0x44 0x46 ("%PDF")
    And PDF 檔大小應大於 5000 byte

  Scenario Outline: 不同欄位填寫組合下 ContractTemplateRenderer 之 HTML 輸出
    Given 已建立 ContractRenderData，Owner.EmergencyContactName="<姓名>"、EmergencyContactRelationship="<關係>"、EmergencyContactPhone="<電話>"
    When 呼叫 ContractTemplateRenderer.Render(data)
    Then HTML 中新 page 1「緊急聯絡人」應顯示 "<PDF姓名>"
    And HTML 中新 page 1「與飼主關係」應顯示 "<PDF關係>"
    And HTML 中新 page 1「緊急聯絡電話」應顯示 "<PDF電話>"

    Examples:
      | 姓名   | 關係 | 電話       | PDF姓名 | PDF關係 | PDF電話     |
      |        |      |            |         |         |             |
      | 李大華 |      |            | 李大華  |         |             |
      |        | 父親 |            |         | 父親    |             |
      | 李大華 | 父親 | 0912345678 | 李大華  | 父親    | 0912345678  |

  # ===== UI 層級（Wpf.UiTests / E2E） =====

  @ui
  Scenario: OwnerPageView 三欄不顯示必填紅星或必填提示
    Given 使用者已啟動 PetSalon.Wpf.exe 並點選 nav-owner 導覽至飼主管理頁
    When 使用者點擊 btn-new-owner 按鈕開啟新增飼主表單
    Then "txt-owner-emergency-name" 對應之 Label 不應顯示「*」紅星
    And "txt-owner-emergency-name" 對應之 Label 不應顯示「必填」字樣
    And "txt-owner-emergency-phone" 對應之 Label 不應顯示「*」紅星
    And "txt-owner-emergency-relationship" 對應之 Label 不應顯示「*」紅星

  @ui
  Scenario: OwnerPageView 三欄全空仍可點擊 btn-save-owner 並儲存成功
    Given 使用者已點擊 btn-new-owner 開啟新增飼主表單
    When 使用者在 txt-owner-name 輸入 "王小明"
    And 使用者在 txt-owner-national-id 輸入 "A123456789"
    And 使用者在 txt-owner-phone 輸入 "0912345678"
    And 使用者在 txt-owner-address 輸入 "桃園市桃園區慈文路322巷5號"
    And 使用者保留 txt-owner-emergency-name / txt-owner-emergency-phone / txt-owner-emergency-relationship 皆為空白
    And 使用者點擊 btn-save-owner 按鈕
    Then 畫面不應彈出任何驗證錯誤對話框
    And list-owners 清單應出現一筆新增之 "王小明" 項目

  @ui
  Scenario: 將既有飼主的緊急聯絡人三欄清空後仍可儲存
    Given list-owners 中已存在 "王小明" 且其緊急聯絡人三欄皆已填寫
    When 使用者於 list-owners 點選 "王小明"
    And 使用者將 txt-owner-emergency-name / txt-owner-emergency-phone / txt-owner-emergency-relationship 三欄全部清空
    And 使用者點擊 btn-save-owner 按鈕
    Then 畫面不應彈出任何驗證錯誤對話框
    And 重新讀取該 Owner 後，三欄應皆為空字串
