# language: zh-TW
# Generated by sa-expert
# Source: pm/owner-deletion.feature
# Project: WPF MVVM（無 HTTP Controller / Route）
# Technical flow: OwnerPageView → OwnerPageViewModel → OwnerService → IPetSalonDbContext → SQLite

Feature: 安全刪除誤建飼主資料技術規格
  對應 View：src/PetSalon.Wpf/Views/OwnerPageView.xaml
  對應 ViewModel：src/PetSalon.Wpf/ViewModels/OwnerPageViewModel.cs
  對應 Service：src/PetSalon.Core/Services/OwnerService.cs
  資料實體：Owner → owners、Pet → pets、Appointment → appointments、GroomingRecord → grooming_records
  既有關聯：Owner/Pet 至 Appointment 皆為 DeleteBehavior.Restrict
  刪除策略：保留 Restrict；服務層檢查歷史後於單次 SaveChangesAsync 明確 RemoveRange(Pets) 再 Remove(Owner)

  Background:
    Given 使用 SQLite in-memory 建立 PetSalonDbContext 並執行 EnsureCreated
    And OwnerService 使用同一個 scoped IPetSalonDbContext 執行刪除
    And OwnerPageViewModel 使用 IDialogService 顯示確認與結果

  Scenario: OwnerPageView 應提供刪除選定飼主的按鈕
    Given OwnerPageViewModel.SelectedOwner 不為 null
    When 檢查 OwnerPageView 的 UI Automation tree
    Then 應存在 AutomationId「btn-delete-owner」的按鈕
    And 按鈕應繫結 DeleteOwnerCommand

  Scenario: 刪除確認應包含姓名、寵物數量及不可復原提示
    Given SelectedOwner.Name 為「王小明」
    And OwnerPets.Count 為 2
    When 執行 DeleteOwnerCommand
    Then IDialogService.Confirm 應收到包含「王小明」、「2」與「無法復原」的訊息

  Scenario: 使用者取消時不應呼叫 OwnerService.DeleteAsync
    Given IDialogService.Confirm 回傳 false
    When 執行 DeleteOwnerCommand
    Then OwnerService.DeleteAsync 不應執行
    And owners 與 pets 應保持不變

  Scenario: 沒有歷史時在單一 SaveChangesAsync 刪除 Pets 與 Owner
    Given owners 有一筆 OwnerId「owner_1」
    And pets 有兩筆 OwnerId「owner_1」的 Pet
    And appointments 不存在 OwnerId「owner_1」或兩隻 PetId 的資料
    When 呼叫 OwnerService.DeleteAsync("owner_1")
    Then IPetSalonDbContext 應先 RemoveRange 該兩筆 Pet 再 Remove Owner
    And 應只呼叫一次 SaveChangesAsync
    And owners 不應存在 OwnerId「owner_1」
    And pets 不應存在 OwnerId「owner_1」

  Scenario Outline: 有預約或美容紀錄時服務層應阻擋刪除
    Given OwnerId「owner_1」或其 Pet 已有「<歷史類型>」
    When 呼叫 OwnerService.DeleteAsync("owner_1")
    Then 應拋出 Code 為 OWNER_HAS_HISTORY 的 AppException
    And owners、pets、appointments 與 grooming_records 都應保持不變

    Examples:
      | 歷史類型     |
      | Appointment  |
      | GroomingRecord |

  Scenario: ViewModel 應將 OWNER_HAS_HISTORY 顯示為不可刪除原因
    Given OwnerService.DeleteAsync 拋出 Code 為 OWNER_HAS_HISTORY 的 AppException
    When OwnerPageViewModel 執行 DeleteOwnerCommand
    Then 畫面應顯示「已有預約或美容紀錄，無法永久刪除」
    And SelectedOwner 與 OwnerPets 應保持目前選取狀態

  Scenario: 刪除成功後清除選取並重新整理列表
    Given IDialogService.Confirm 回傳 true
    And OwnerService.DeleteAsync 成功
    When DeleteOwnerCommand 完成
    Then SelectedOwner 應為 null
    And OwnerPets 應為空集合
    And Owners 應重新從 OwnerService.ListAsync 載入
    And IDialogService.Success 應顯示刪除完成

  Scenario: SaveChangesAsync 失敗時 EF 交易應保留 Owner 與 Pets
    Given OwnerId「owner_1」與其 Pets 符合刪除條件
    And SaveChangesAsync 在提交前失敗
    When 呼叫 OwnerService.DeleteAsync("owner_1")
    Then 呼叫端應收到例外
    And 使用新的 DbContext 查詢時 Owner 與 Pets 應仍存在
