# language: zh-TW
# Generated by sa-expert
# Source: pm/shop-signature-role-split.feature
# Project: WPF MVVM + file store + PuppeteerSharp/Handlebars PDF
# Technical flow: SignatureSettingsViewModel → ShopSignatureService → IShopSignatureStore
# PDF flow: ContractGenerateDialogViewModel → ContractService → ContractRenderData.GroomerSignaturePng / ManagerSignaturePng → ContractTemplateRenderer → contract.hbs

Feature: 分別記錄美容人員與負責人簽名 技術規格
  新增列舉：PetSalon.Core.Dtos.SignatureRole { Groomer, Manager }
  異動 DTO：ShopSignatureProfile.Role（init 屬性，預設 Groomer）
  異動 DTO：ContractShopSignatures(GroomerPng, ManagerPng) 取代單一 ShopSignaturePng
  異動抽象：ContractRenderData.GroomerSignaturePng / ManagerSignaturePng
  異動服務：ShopSignatureService（角色化 Create/SetDefault/Delete/ChangeRole/GetDefault）
  異動 UI：SignatureSettingsView（角色下拉）、ContractGenerateDialog（兩組簽名下拉）
  異動模板：contract.hbs 使用 groomerSignatureDataUrl 與 managerSignatureDataUrl
  儲存位置不變：{app-data}/signatures/profiles.json 與 {signature-id}.png
  資料庫異動：無

  Background:
    Given 測試以暫存 app-data 建立 signatures 目錄
    And ShopSignatureOptions.RootDir 指向該 signatures 目錄
    And PDF 測試可直接呼叫 ContractTemplateRenderer.Render 取得 HTML

  Scenario: profiles.json 缺少 role 欄位時應反序列化為 Groomer
    Given profiles.json 是升級前寫入、entry 沒有 role 欄位
    When 呼叫 ShopSignatureService.ListAsync
    Then 每個 ShopSignatureProfile.Role 應為 SignatureRole.Groomer
    And 原有的 IsDefault 值應保持不變

  Scenario: CreateAsync 應接受角色並只在該角色缺預設時自動設為預設
    Given signatures 目錄已有一組 Groomer profile 且為 Groomer 預設
    When 呼叫 CreateAsync(name, SignatureRole.Manager, pngBytes)
    Then 新 profile 的 Role 應為 Manager
    And 新 profile 的 IsDefault 應為 true（Manager 的第一組）
    And 既有 Groomer 預設的 IsDefault 應維持 true

  Scenario: SetDefaultAsync 只影響同角色的 profile
    Given Groomer 有「小美」「小華」，Manager 有「店長」
    And 「小美」為 Groomer 預設、「店長」為 Manager 預設
    When 呼叫 SetDefaultAsync(小華的 SignatureId)
    Then Groomer 中僅「小華」的 IsDefault 為 true
    And 「店長」的 IsDefault 仍為 true

  Scenario: ChangeRoleAsync 應搬移角色並修復兩邊的預設
    Given Groomer 有「小美」（預設）與「小華」，Manager 尚無 profile
    When 呼叫 ChangeRoleAsync(小美的 SignatureId, SignatureRole.Manager)
    Then 「小美」的 Role 應為 Manager 且 IsDefault 為 true
    And 「小華」應遞補成為 Groomer 預設
    And PNG 檔名與 SignatureId 不應改變

  Scenario: DeleteAsync 只在同角色內遞補預設
    Given Groomer 有「小美」（預設）與「小華」，Manager 有「店長」（預設）
    When 呼叫 DeleteAsync(小美的 SignatureId)
    Then 「小華」的 IsDefault 應為 true
    And 「店長」的 IsDefault 應維持 true

  Scenario: 刪除某角色最後一組 profile 後該角色沒有預設
    Given Manager 只有「店長」一組 profile
    When 呼叫 DeleteAsync(店長的 SignatureId)
    Then GetDefaultAsync(SignatureRole.Manager) 應回傳 null
    And GetDefaultAsync(SignatureRole.Groomer) 不應受影響

  Scenario: 契約對話框應載入兩份清單與兩個預設
    Given ListAsync 回傳 Groomer 與 Manager 各若干 profile
    When ContractGenerateDialogViewModel.LoadPreviewAsync 執行
    Then GroomerSignatures 應只含 Role 為 Groomer 的 profile
    And ManagerSignatures 應只含 Role 為 Manager 的 profile
    And SelectedGroomerSignature 應為 Groomer 預設
    And SelectedManagerSignature 應為 Manager 預設
    And ContractService.PreviewAsync 應收到含兩份 bytes 的 ContractShopSignatures

  Scenario: 只切換其中一個角色時另一個快照不變
    Given 目前預覽使用 ContractShopSignatures(小美 bytes, 店長 bytes)
    When SelectedGroomerSignature 改為「小華」
    Then 新的 ContractShopSignatures.GroomerPng 應為「小華」bytes
    And ContractShopSignatures.ManagerPng 應仍為「店長」bytes
    And 舊 preview 暫存檔應安全刪除

  Scenario: ContractTemplateRenderer 應輸出兩個獨立 data URI
    Given ContractRenderData.GroomerSignaturePng 與 ManagerSignaturePng 為不同的合法 PNG bytes
    When ContractTemplateRenderer.Render 產生 HTML
    Then 「美容人員簽名」欄應包含 groomerSignatureDataUrl 圖片
    And 「乙方簽章」欄應包含 managerSignatureDataUrl 圖片
    And 兩個 data URI 各自只應出現一次
    And 飼主簽名與甲方簽章區不應包含任何簽名圖片

  Scenario Outline: 單邊為 null 時只有該欄位留白
    Given ContractRenderData.<有值欄位> 為合法 PNG bytes
    And ContractRenderData.<留白欄位> 為 null
    When ContractTemplateRenderer.Render 產生 HTML
    Then 「<有值欄位對應區塊>」應包含 signature-img
    And 「<留白欄位對應區塊>」應為空白 span

    Examples:
      | 有值欄位              | 留白欄位              | 有值欄位對應區塊 | 留白欄位對應區塊 |
      | GroomerSignaturePng   | ManagerSignaturePng   | 美容人員簽名     | 乙方簽章         |
      | ManagerSignaturePng   | GroomerSignaturePng   | 乙方簽章         | 美容人員簽名     |

  Scenario: CommitPreviewAsync 應沿用最後預覽的 ContractShopSignatures
    Given ContractGenerateDialogViewModel 已以某組 ContractShopSignatures 產生最新預覽
    When 執行 GenerateCommand
    Then ContractService.CommitPreviewAsync 應收到同一個 ContractShopSignatures 快照
    And 正式 PDF 的兩個簽名 data URI 應與預覽一致
    And GroomingRecord.ContractPaths 仍只新增既有格式的 ContractVersion

  Scenario Outline: 單一角色簽名讀取失敗時只降級該欄位
    Given SelectedGroomerSignature 指向「<錯誤類型>」的簽名檔
    And SelectedManagerSignature 可正常讀取
    When ContractGenerateDialogViewModel 嘗試讀取簽名
    Then IDialogService.Warning 應顯示該角色簽名無法使用
    And ContractShopSignatures.GroomerPng 應為 null
    And ContractShopSignatures.ManagerPng 應為負責人簽名 bytes
    And 使用者仍可執行 GenerateCommand

    Examples:
      | 錯誤類型 |
      | 遺失     |
      | 毀損     |
      | 無法讀取 |
