# language: zh-TW
# Generated by sa-expert
# Source: pm/shop-signature-pdf.feature
# Project: WPF MVVM + file store + PuppeteerSharp/Handlebars PDF
# Technical flow: SignatureSettingsViewModel（planned）→ ShopSignatureService（planned）→ IShopSignatureStore（planned）
# PDF flow: ContractGenerateDialogViewModel → ContractService → ContractRenderData.ShopSignaturePng（planned）→ ContractTemplateRenderer → contract.hbs

Feature: 保存店家簽名並套用契約 PDF 技術規格
  對應既有控制項：src/PetSalon.Wpf/Controls/SignaturePad.xaml(.cs)
  對應既有 PDF：IPdfGenerator、ContractService、ContractTemplateRenderer、contract.hbs
  對應既有備份：BackupService、BackupOptions
  預計新增抽象：IShopSignatureStore
  預計新增服務：ShopSignatureService
  預計新增 UI：SignatureSettingsView / SignatureSettingsViewModel
  儲存位置：{PETSALON_APP_DATA 或 LocalApplicationData/PetSalon}/signatures/profiles.json 與 {signature-id}.png
  資料庫異動：無

  Background:
    Given 測試以暫存 app-data 建立 signatures 目錄
    And ShopSignatureOptions.RootDir 指向該 signatures 目錄
    And PDF 測試可直接呼叫 ContractTemplateRenderer.Render 取得 HTML

  Scenario: SignaturePad 手寫輸出應正規化為透明 PNG
    Given SignaturePad.Ink 有至少一筆 Stroke
    When 呼叫簽名擷取與正規化流程
    Then 輸出 bytes 應具有 PNG magic header
    And 圖片背景應為透明且內容已裁切至簽名邊界
    And 輸出應符合 ShopSignatureOptions 的尺寸與檔案大小限制

  Scenario Outline: PNG 與 JPEG 匯入後應重新編碼為 PNG
    Given 輸入檔可由 WPF BitmapDecoder 解碼為「<格式>」
    When SignatureSettingsViewModel 執行 ImportSignatureCommand
    Then 傳入 ShopSignatureService 的內容應為 PNG bytes
    And FileShopSignatureStore 應在 RootDir 寫入「{signature-id}.png」
    And profiles.json 應新增只含相對 PNG 路徑的 profile

    Examples:
      | 格式 |
      | PNG  |
      | JPEG |

  Scenario Outline: 不合法輸入不得建立 profile 或殘留檔案
    Given 匯入內容為「<不合法類型>」
    When 嘗試建立 ShopSignatureProfile
    Then 應拋出 Code 為 INVALID_SIGNATURE_IMAGE 的 AppException
    And profiles.json 不應新增 profile
    And signatures 目錄不應殘留新的 PNG 或暫存檔
    And 例外訊息不應包含 Base64

    Examples:
      | 不合法類型     |
      | SVG            |
      | HTML           |
      | 毀損圖片       |
      | 超出設定上限   |

  Scenario: profile 與 PNG 應以原子流程保存
    Given ShopSignatureService 收到合法 profile 名稱與 PNG bytes
    When 呼叫 CreateAsync
    Then 應先寫入 RootDir 內的暫存檔
    And PNG 與 profiles.json 都成功後才視為 ShopSignatureProfile 已建立
    And 任一步驟失敗時不應留下可見的半套 profile

  Scenario: 設定新預設時 profiles.json 最多只有一個 IsDefault=true
    Given profiles.json 有「店主」與「媽媽」兩組 profile
    And 「店主」的 IsDefault 為 true
    When 呼叫 ShopSignatureService.SetDefaultAsync(媽媽的 SignatureId)
    Then 「媽媽」的 IsDefault 應為 true
    And 其他所有 profile 的 IsDefault 應為 false

  Scenario: 刪除預設 profile 後預設保持空缺
    Given 「媽媽」為預設且「店主」不是預設
    When 呼叫 ShopSignatureService.DeleteAsync(媽媽的 SignatureId)
    Then 「媽媽」的 metadata 與 PNG 應刪除
    And 「店主」的 IsDefault 仍應為 false
    And 所有解析後的刪除路徑都必須位於 ShopSignatureOptions.RootDir

  Scenario: 契約預覽對話框應載入 profile 清單與預設值
    Given ShopSignatureService.ListAsync 回傳多組 profile 且「媽媽」為預設
    When ContractGenerateDialogViewModel.LoadPreviewAsync 執行
    Then AvailableSignatures 應包含所有 profile
    And SelectedSignatureId 應等於「媽媽」的 SignatureId
    And PreviewSignaturePng 應為「媽媽」簽名的 bytes 快照

  Scenario: 切換 profile 時應以新快照重新產生預覽
    Given PreviewSignaturePng 目前是「媽媽」簽名
    When SelectedSignatureId 改為「店主」
    Then 應讀取「店主」簽名 bytes 至新的 PreviewSignaturePng
    And ContractService.PreviewAsync 應以該 bytes 重新產生 PreviewPath
    And 舊 preview 暫存檔應安全刪除

  Scenario: ContractRenderData 應分離 OwnerSignaturePng 與 ShopSignaturePng
    Given ContractRenderData.OwnerSignaturePng 為 null
    And ContractRenderData.ShopSignaturePng 為合法 PNG bytes
    When ContractTemplateRenderer.Render 產生 HTML
    Then HTML 的美容人員簽名區應包含 shopSignatureDataUrl 圖片
    And HTML 的乙方簽章區應包含相同 shopSignatureDataUrl 圖片
    And HTML 的飼主簽名與甲方簽章區不應包含任何簽名圖片

  Scenario: CommitPreviewAsync 應使用最後預覽的同一份 bytes
    Given ContractGenerateDialogViewModel 已以 PreviewSignaturePng 產生最新預覽
    When 執行 GenerateCommand
    Then ContractService.CommitPreviewAsync 應收到同一個 PreviewSignaturePng 快照
    And 正式 PDF 的兩個店家簽名 data URI 應與預覽一致
    And GroomingRecord.ContractPaths 仍只新增既有格式的 ContractVersion

  Scenario: 沒有選定簽名時維持 R2 空白且不阻擋
    Given SelectedSignatureId 與 PreviewSignaturePng 都為 null
    When ContractService.PreviewAsync 與 CommitPreviewAsync 執行
    Then ContractRenderData.ShopSignaturePng 應為 null
    And contract.hbs 的四個簽名位置都不應包含 data:image/png;base64
    And 應成功建立預覽及正式 PDF

  Scenario Outline: 簽名讀取失敗時警告並降級為空白
    Given SelectedSignatureId 指向「<錯誤類型>」的簽名檔
    When ContractGenerateDialogViewModel 嘗試讀取簽名
    Then IDialogService.Warning 應顯示簽名無法使用
    And PreviewSignaturePng 應設為 null
    And 使用者仍可執行 GenerateCommand

    Examples:
      | 錯誤類型 |
      | 遺失     |
      | 毀損     |
      | 無法讀取 |

  Scenario: BackupService.CreateAsync 應封裝 signatures 目錄
    Given SignaturesDir 含 profiles.json 與多個 PNG
    When BackupService.CreateAsync 建立 zip
    Then zip 應包含 signatures/profiles.json
    And zip 應包含每個相對路徑的 signatures/{signature-id}.png

  Scenario: BackupService.RestoreAsync 應安全還原 signatures 目錄
    Given 備份 zip 含合法的 signatures entries
    When BackupService.RestoreAsync 在乾淨 SignaturesDir 還原
    Then profiles.json 與所有 PNG 應還原
    And profile 預設值應保持一致
    And 任一 entry 解析後若超出 SignaturesDir 應以 INVALID_PATH 拒絕
