// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetSalon.Infrastructure.Persistence;

#nullable disable

namespace PetSalon.Infrastructure.Migrations
{
    [DbContext(typeof(PetSalonDbContext))]
    [Migration("20260516062022_AddPhysicalExaminationNotes")]
    partial class AddPhysicalExaminationNotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("PetSalon.Core.Entities.Appointment", b =>
                {
                    b.Property<string>("AppointmentId")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("CancelReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("PetId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AppointmentId");

                    b.HasIndex("Date");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PetId", "Date");

                    b.ToTable("appointments", (string)null);
                });

            modelBuilder.Entity("PetSalon.Core.Entities.GroomingRecord", b =>
                {
                    b.Property<string>("GroomingRecordId")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("AppointmentId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CashPayment")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("ContractPaths")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicalHistory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicalHistoryOther")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherNotes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerNotes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Personality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("ServiceTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Services")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShopNotes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StoredValueDeduction")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("GroomingRecordId");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("grooming_records", (string)null);
                });

            modelBuilder.Entity("PetSalon.Core.Entities.Owner", b =>
                {
                    b.Property<string>("OwnerId")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactPhone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyContactRelationship")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsStoredValueCustomer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredAnimalHospitalAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredAnimalHospitalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredAnimalHospitalPhone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StoredValueBalance")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("OwnerId");

                    b.HasIndex("Name");

                    b.ToTable("owners", (string)null);
                });

            modelBuilder.Entity("PetSalon.Core.Entities.Pet", b =>
                {
                    b.Property<string>("PetId")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChipNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsNeutered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MedicalHistory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicalHistoryOther")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Personality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("UnregisteredIdMethod")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("PetId");

                    b.HasIndex("Name");

                    b.HasIndex("OwnerId");

                    b.ToTable("pets", (string)null);
                });

            modelBuilder.Entity("PetSalon.Core.Entities.Appointment", b =>
                {
                    b.HasOne("PetSalon.Core.Entities.Owner", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetSalon.Core.Entities.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetSalon.Core.Entities.GroomingRecord", b =>
                {
                    b.HasOne("PetSalon.Core.Entities.Appointment", "Appointment")
                        .WithOne("GroomingRecord")
                        .HasForeignKey("PetSalon.Core.Entities.GroomingRecord", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PetSalon.Core.Entities.PhysicalExamination", "PhysicalExamination", b1 =>
                        {
                            b1.Property<string>("GroomingRecordId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Ears")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("phys_ears");

                            b1.Property<string>("EarsNote")
                                .HasMaxLength(30)
                                .HasColumnType("TEXT")
                                .HasColumnName("phys_ears_note");

                            b1.Property<string>("Eyes")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("phys_eyes");

                            b1.Property<string>("EyesNote")
                                .HasMaxLength(30)
                                .HasColumnType("TEXT")
                                .HasColumnName("phys_eyes_note");

                            b1.Property<string>("Fur")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("phys_fur");

                            b1.Property<string>("FurNote")
                                .HasMaxLength(30)
                                .HasColumnType("TEXT")
                                .HasColumnName("phys_fur_note");

                            b1.Property<string>("Limbs")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("phys_limbs");

                            b1.Property<string>("LimbsNote")
                                .HasMaxLength(30)
                                .HasColumnType("TEXT")
                                .HasColumnName("phys_limbs_note");

                            b1.Property<string>("Skin")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("phys_skin");

                            b1.Property<string>("SkinNote")
                                .HasMaxLength(30)
                                .HasColumnType("TEXT")
                                .HasColumnName("phys_skin_note");

                            b1.Property<string>("Teeth")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("phys_teeth");

                            b1.Property<string>("TeethNote")
                                .HasMaxLength(30)
                                .HasColumnType("TEXT")
                                .HasColumnName("phys_teeth_note");

                            b1.HasKey("GroomingRecordId");

                            b1.ToTable("grooming_records");

                            b1.WithOwner()
                                .HasForeignKey("GroomingRecordId");
                        });

                    b.Navigation("Appointment");

                    b.Navigation("PhysicalExamination")
                        .IsRequired();
                });

            modelBuilder.Entity("PetSalon.Core.Entities.Pet", b =>
                {
                    b.HasOne("PetSalon.Core.Entities.Owner", "Owner")
                        .WithMany("Pets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("PetSalon.Core.Entities.PhysicalExamination", "PhysicalExamination", b1 =>
                        {
                            b1.Property<string>("PetId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Ears")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("phys_ears");

                            b1.Property<string>("EarsNote")
                                .HasMaxLength(30)
                                .HasColumnType("TEXT")
                                .HasColumnName("phys_ears_note");

                            b1.Property<string>("Eyes")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("phys_eyes");

                            b1.Property<string>("EyesNote")
                                .HasMaxLength(30)
                                .HasColumnType("TEXT")
                                .HasColumnName("phys_eyes_note");

                            b1.Property<string>("Fur")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("phys_fur");

                            b1.Property<string>("FurNote")
                                .HasMaxLength(30)
                                .HasColumnType("TEXT")
                                .HasColumnName("phys_fur_note");

                            b1.Property<string>("Limbs")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("phys_limbs");

                            b1.Property<string>("LimbsNote")
                                .HasMaxLength(30)
                                .HasColumnType("TEXT")
                                .HasColumnName("phys_limbs_note");

                            b1.Property<string>("Skin")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("phys_skin");

                            b1.Property<string>("SkinNote")
                                .HasMaxLength(30)
                                .HasColumnType("TEXT")
                                .HasColumnName("phys_skin_note");

                            b1.Property<string>("Teeth")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("phys_teeth");

                            b1.Property<string>("TeethNote")
                                .HasMaxLength(30)
                                .HasColumnType("TEXT")
                                .HasColumnName("phys_teeth_note");

                            b1.HasKey("PetId");

                            b1.ToTable("pets");

                            b1.WithOwner()
                                .HasForeignKey("PetId");
                        });

                    b.Navigation("Owner");

                    b.Navigation("PhysicalExamination")
                        .IsRequired();
                });

            modelBuilder.Entity("PetSalon.Core.Entities.Appointment", b =>
                {
                    b.Navigation("GroomingRecord");
                });

            modelBuilder.Entity("PetSalon.Core.Entities.Owner", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
