// Auto-generated by sa-expert
// Feature: R1 緊急聯絡人欄位取消必填
// Source: sa/sa-feedback-r1-emergency-contact-optional.feature
// Module type: WPF MVVM + EF Core SQLite + Handlebars PDF
// Architecture: OwnerService → PetSalonDbContext → SQLite; ContractTemplateRenderer → contract.hbs
//
// BDD 風格：xUnit v3 [Fact] / [Theory] 一對一對應 sa-*.feature 之 Scenario / Scenario Outline。

using System.Text.RegularExpressions;
using FluentAssertions;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using PetSalon.Core.Abstractions;
using PetSalon.Core.Dtos;
using PetSalon.Core.Entities;
using PetSalon.Core.Services;
using PetSalon.Core.Tests.Helpers;
using PetSalon.Infrastructure.Pdf;
using PetSalon.Infrastructure.Persistence;
using Xunit;

namespace PetSalon.Core.Tests.StepDefinitions;

[Trait("feature", "R1-EmergencyContactOptional")]
public partial class R1EmergencyContactSteps : IDisposable
{
    // === Shared fixture / state ===
    private readonly string _tempDir;
    private readonly string _templatePath;
    private readonly string _fontPath;

    public R1EmergencyContactSteps()
    {
        _tempDir = Path.Combine(Path.GetTempPath(), "r1-test-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(_tempDir);

        var infraOutput = Path.GetDirectoryName(typeof(PuppeteerSharpContractGenerator).Assembly.Location)!;
        _templatePath = Path.Combine(infraOutput, "Pdf", "Templates", "contract.hbs");
        _fontPath = Path.Combine(infraOutput, "Pdf", "Assets", "kaiu.ttf");
    }

    public void Dispose()
    {
        if (Directory.Exists(_tempDir)) Directory.Delete(_tempDir, recursive: true);
    }

    // === Helper: in-memory SQLite db for service tests ===
    private static (PetSalonDbContext db, SqliteConnection conn) CreateDb()
    {
        var connection = new SqliteConnection("DataSource=:memory:");
        connection.Open();
        var options = new DbContextOptionsBuilder<PetSalonDbContext>()
            .UseSqlite(connection)
            .Options;
        var db = new PetSalonDbContext(options);
        db.Database.EnsureCreated();
        return (db, connection);
    }

    // === Helper: 建立可變動的範例 ContractRenderData，供各 Scenario 客製化欄位 ===
    private static ContractRenderData SampleData(
        string emergencyName = "李四",
        string emergencyPhone = "0987654321",
        string emergencyRelationship = "配偶")
    {
        var owner = new Owner
        {
            OwnerId = "owner_r1", Name = "王小明", NationalId = "A123456789",
            Phone = "0912345678", Address = "桃園市桃園區慈文路322巷5號",
            EmergencyContactName = emergencyName,
            EmergencyContactPhone = emergencyPhone,
            EmergencyContactRelationship = emergencyRelationship,
        };
        var pet = new Pet { PetId = "pet_r1", OwnerId = owner.OwnerId, Name = "小白", Species = "犬", Breed = "柴犬", Gender = "公", Age = "3 歲" };
        var appt = new Appointment { AppointmentId = "appt_r1", OwnerId = owner.OwnerId, PetId = pet.PetId, Date = new DateOnly(2026, 5, 16), Time = new TimeOnly(10, 0) };
        var rec = new GroomingRecord { GroomingRecordId = "rec_r1", AppointmentId = appt.AppointmentId, ServiceDate = appt.Date, ServiceTime = appt.Time };
        return new ContractRenderData(owner, pet, appt, rec, Array.Empty<byte>(),
            owner.PreferredAnimalHospitalName, owner.PreferredAnimalHospitalPhone, owner.PreferredAnimalHospitalAddress);
    }

    // ===== Scenario: OwnerService 對三欄全空之 Owner 寫入不應拋例外 =====
    [Fact(DisplayName = "R1 / OwnerService 對三欄全空之 Owner 寫入不應拋例外")]
    public async Task OwnerService_SaveAsync_with_three_emergency_fields_empty_does_not_throw()
    {
        var (db, conn) = CreateDb();
        using var _ = conn;
        await using var _db = db;
        var ids = new SequentialIdGenerator();
        var clock = new FakeClock();
        var svc = new OwnerService(db, ids, clock);

        // Given EmergencyContact 三欄皆為空字串
        var input = new OwnerInput
        {
            Name = "王小明",
            NationalId = "A123456789",
            Phone = "0912345678",
            Address = "桃園市桃園區慈文路322巷5號",
            EmergencyContactName = "",
            EmergencyContactPhone = "",
            EmergencyContactRelationship = "",
        };

        // When
        var owner = await svc.CreateAsync(input);

        // Then 不應拋例外，且三欄皆為空字串
        owner.OwnerId.Should().StartWith("owner_");
        owner.EmergencyContactName.Should().Be("");
        owner.EmergencyContactPhone.Should().Be("");
        owner.EmergencyContactRelationship.Should().Be("");

        // And SQLite 中確實存在
        var loaded = await svc.GetByIdAsync(owner.OwnerId);
        loaded.EmergencyContactName.Should().Be("");
        loaded.EmergencyContactPhone.Should().Be("");
        loaded.EmergencyContactRelationship.Should().Be("");
    }

    // ===== Scenario: OwnerService 對既有 Owner 清空三欄之 Update 不應拋例外 =====
    [Fact(DisplayName = "R1 / OwnerService 對既有 Owner 清空三欄之 Update 不應拋例外")]
    public async Task OwnerService_SaveAsync_updating_existing_owner_to_clear_emergency_fields_does_not_throw()
    {
        var (db, conn) = CreateDb();
        using var _ = conn;
        await using var _db = db;
        var ids = new SequentialIdGenerator();
        var clock = new FakeClock();
        var svc = new OwnerService(db, ids, clock);

        // Given 已存在 "王小明"，三欄皆填
        var createInput = new OwnerInput
        {
            Name = "王小明",
            NationalId = "A123456789",
            Phone = "0912345678",
            Address = "桃園市桃園區慈文路322巷5號",
            EmergencyContactName = "李四",
            EmergencyContactPhone = "0987654321",
            EmergencyContactRelationship = "配偶",
        };
        var created = await svc.CreateAsync(createInput);

        // When 將三欄改為空字串
        var updateInput = new OwnerInput
        {
            Name = "王小明",
            NationalId = "A123456789",
            Phone = "0912345678",
            Address = "桃園市桃園區慈文路322巷5號",
            EmergencyContactName = "",
            EmergencyContactPhone = "",
            EmergencyContactRelationship = "",
        };
        var updated = await svc.UpdateAsync(created.OwnerId, updateInput);

        // Then 不應拋例外，三欄皆更新為空字串
        updated.EmergencyContactName.Should().Be("");
        updated.EmergencyContactPhone.Should().Be("");
        updated.EmergencyContactRelationship.Should().Be("");
    }

    // ===== Scenario: ContractTemplateRenderer 對三欄全空之 Owner 渲染後 HTML 不應包含 null / 未填寫 / "-" =====
    [Fact(DisplayName = "R1 / Renderer 對三欄全空之 Owner 渲染後 HTML 不應包含佔位字串")]
    public void Renderer_does_not_output_placeholder_for_empty_emergency_fields()
    {
        // Given Owner.EmergencyContactName = "" 且其餘兩欄也為空
        var data = SampleData(emergencyName: "", emergencyPhone: "", emergencyRelationship: "");
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);

        // When 呼叫 Render(data)
        var html = renderer.Render(data);

        // Then HTML 不應出現 "null"、"未填寫"、樣板殘留 "{{owner.emergencyContactName}}"
        html.Should().NotContain("null");
        html.Should().NotContain("未填寫");
        html.Should().NotContain("{{owner.emergencyContactName}}");

        // 緊急聯絡人 <td class="val"> 中三欄皆為空白（不含多餘字符）
        // page1 的緊急聯絡人儲存格（<td class="val" colspan="5">{{owner.emergencyContactName}}</td>）應為空
        html.Should().MatchRegex(@"<td class=""label"">緊急聯絡人</td>\s*<td class=""val"" colspan=""5""></td>");
    }

    // ===== Scenario: EmergencyContactName 有值但 Relationship 為空時不輸出空括號 =====
    [Fact(DisplayName = "R1 / Renderer EmergencyContactName 有值但 Relationship 為空時不輸出空括號")]
    public void Renderer_does_not_output_empty_parentheses_when_relationship_is_empty()
    {
        // Given Owner.EmergencyContactName = "李大華" 且 EmergencyContactRelationship = ""
        var data = SampleData(emergencyName: "李大華", emergencyPhone: "", emergencyRelationship: "");
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);

        // When
        var html = renderer.Render(data);

        // Then 含「李大華」但不含「()」空括號
        html.Should().Contain("李大華");
        html.Should().NotContain("()");
    }

    // ===== Scenario: 新 page 1（R4 重排序後）服務資料表三列空值 =====
    [Fact(DisplayName = "R1 / Renderer 新 page 1 服務資料表三列空值不應顯示 null 或未填寫")]
    public void Renderer_new_page1_service_record_shows_blank_for_empty_emergency_fields()
    {
        // Given Owner 三欄皆空
        var data = SampleData(emergencyName: "", emergencyPhone: "", emergencyRelationship: "");
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);

        // When
        var html = renderer.Render(data);

        // Then 整個 HTML 不應出現 "null" 或 "未填寫"
        html.Should().NotContain("null");
        html.Should().NotContain("未填寫");

        // page2 的 (二) 消費者/飼主 section 中 emergencyContactName 儲存格應為空白
        // 該 section 的 "緊急聯絡人" td 後緊接的 td 應不含實際文字
        var page2Start = html.IndexOf("(二) 消費者/飼主", StringComparison.Ordinal);
        if (page2Start >= 0)
        {
            var excerpt = html.Substring(page2Start, Math.Min(1000, html.Length - page2Start));
            excerpt.Should().NotContain("null");
            excerpt.Should().NotContain("未填寫");
        }
    }

    // ===== Scenario: PuppeteerSharpContractGenerator 對三欄空之 Owner 應產生有效 PDF =====
    [Fact(DisplayName = "R1 / PuppeteerSharp 對三欄空之 Owner 應產出有效 PDF")]
    [Trait("category", "integration")]
    public async Task PuppeteerSharp_generates_valid_pdf_for_owner_with_empty_emergency_fields()
    {
        var data = SampleData(emergencyName: "", emergencyPhone: "", emergencyRelationship: "");
        var cacheDir = Path.Combine(Path.GetTempPath(), "petsalon-test-chromium-cache");

        // When
        await using var gen = new PuppeteerSharpContractGenerator(_templatePath, _fontPath, cacheDir);
        var output = await gen.GenerateContractAsync(data, _tempDir, nextVersion: 1);

        // Then
        File.Exists(output.AbsolutePath).Should().BeTrue();
        var bytes = await File.ReadAllBytesAsync(output.AbsolutePath);
        bytes.Length.Should().BeGreaterThan(5000);
        bytes[0].Should().Be(0x25); bytes[1].Should().Be(0x50);
        bytes[2].Should().Be(0x44); bytes[3].Should().Be(0x46);
    }

    // ===== Scenario Outline: 不同欄位填寫組合下 Renderer 之 HTML 輸出 =====
    [Theory(DisplayName = "R1 / 不同欄位填寫組合下 Renderer 之 HTML 輸出")]
    [InlineData("", "", "", "", "", "")]
    [InlineData("李大華", "", "", "李大華", "", "")]
    [InlineData("", "父親", "", "", "父親", "")]
    [InlineData("李大華", "父親", "0912345678", "李大華", "父親", "0912345678")]
    public void Renderer_emergency_fields_combinations(
        string name, string relationship, string phone,
        string expectedName, string expectedRelationship, string expectedPhone)
    {
        // Given Owner 之三欄為對應 InlineData
        var data = SampleData(emergencyName: name, emergencyPhone: phone, emergencyRelationship: relationship);
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);

        // When
        var html = renderer.Render(data);

        // Then
        // page1 的緊急聯絡人表格
        if (!string.IsNullOrEmpty(expectedName))
            html.Should().Contain(expectedName);
        if (!string.IsNullOrEmpty(expectedRelationship))
            html.Should().Contain(expectedRelationship);
        if (!string.IsNullOrEmpty(expectedPhone))
            html.Should().Contain(expectedPhone);

        // 空值時不應顯示 null
        html.Should().NotContain("null");
        html.Should().NotContain("undefined");
        // 有 relationship 時 page2 應含括號格式，空時不應含 "()"
        if (string.IsNullOrEmpty(relationship))
            html.Should().NotContain("()");
    }
}
