// Auto-generated by sa-expert
// Feature: R2 移除系統內手寫簽名要求
// Source: sa/sa-feedback-r2-remove-system-signature-pad.feature
// Architecture: ContractService → PuppeteerSharpContractGenerator → ContractTemplateRenderer → contract.hbs

using System.Text.RegularExpressions;
using FluentAssertions;
using PetSalon.Core.Abstractions;
using PetSalon.Core.Entities;
using PetSalon.Infrastructure.Pdf;
using Xunit;

namespace PetSalon.Core.Tests.StepDefinitions;

[Trait("feature", "R2-SignaturePadRemoval")]
public partial class R2SignaturePadRemovalSteps : IDisposable
{
    private readonly string _tempDir;
    private readonly string _templatePath;
    private readonly string _fontPath;

    public R2SignaturePadRemovalSteps()
    {
        _tempDir = Path.Combine(Path.GetTempPath(), "r2-test-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(_tempDir);
        var infraOutput = Path.GetDirectoryName(typeof(PuppeteerSharpContractGenerator).Assembly.Location)!;
        _templatePath = Path.Combine(infraOutput, "Pdf", "Templates", "contract.hbs");
        _fontPath = Path.Combine(infraOutput, "Pdf", "Assets", "kaiu.ttf");
    }

    public void Dispose()
    {
        if (Directory.Exists(_tempDir)) Directory.Delete(_tempDir, recursive: true);
    }

    private static ContractRenderData SampleData(byte[]? signatureBytes = null)
    {
        var owner = new Owner { OwnerId = "owner_r2", Name = "王小明", NationalId = "A123456789", Phone = "0912345678", Address = "桃園市桃園區慈文路322巷5號" };
        var pet = new Pet { PetId = "pet_r2", OwnerId = owner.OwnerId, Name = "小白", Species = "犬", Breed = "柴犬", Gender = "公", Age = "3 歲" };
        var appt = new Appointment { AppointmentId = "appt_r2", OwnerId = owner.OwnerId, PetId = pet.PetId, Date = new DateOnly(2026, 5, 16), Time = new TimeOnly(10, 0) };
        var rec = new GroomingRecord { GroomingRecordId = "rec_r2", AppointmentId = appt.AppointmentId, ServiceDate = appt.Date, ServiceTime = appt.Time };
        return new ContractRenderData(owner, pet, appt, rec, signatureBytes ?? Array.Empty<byte>(),
            "安欣動物醫院", "03-3367775", "桃園市桃園區中福街60號");
    }

    [Fact(DisplayName = "R2 / GenerateContractAsync 對空 OwnerSignaturePng 不應阻擋")]
    [Trait("category", "integration")]
    public async Task GenerateContractAsync_with_empty_signature_does_not_block()
    {
        // Given OwnerSignaturePng = Array.Empty<byte>()
        var data = SampleData(Array.Empty<byte>());
        var cacheDir = Path.Combine(Path.GetTempPath(), "petsalon-test-chromium-cache");

        // When
        await using var gen = new PuppeteerSharpContractGenerator(_templatePath, _fontPath, cacheDir);
        var output = await gen.GenerateContractAsync(data, _tempDir, nextVersion: 1);

        // Then 應產出 PDF 檔
        File.Exists(output.AbsolutePath).Should().BeTrue();
        var bytes = await File.ReadAllBytesAsync(output.AbsolutePath);
        bytes[0..4].Should().Equal(new byte[] { 0x25, 0x50, 0x44, 0x46 });
    }

    [Fact(DisplayName = "R2 / Renderer 對空簽名 byte[] 渲染後 HTML 不應出現 data:image/png;base64")]
    public void Renderer_with_empty_signature_does_not_emit_base64_image()
    {
        // Given
        var data = SampleData(Array.Empty<byte>());
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);

        // When
        var html = renderer.Render(data);

        // Then HTML 不應出現 data:image/png;base64,
        html.Should().NotContain("data:image/png;base64,");

        // 4 個簽名線仍以 <span class="blank wide"> 呈現（空內容）
        var matches = Regex.Matches(html, @"<span class=""blank wide"">([^<]*)</span>");
        matches.Should().HaveCountGreaterThanOrEqualTo(4,
            "應存在至少 4 個 .blank.wide span（甲方簽章、乙方簽章、飼主簽名、美容人員簽名）");
        foreach (Match m in matches)
        {
            m.Groups[1].Value.Trim().Should().BeEmpty("每個簽名 span 的內容應為空白");
        }
    }

    [Fact(DisplayName = "R2 / Renderer 對任意 OwnerSignaturePng byte[] 都不應將簽名嵌入 4 個簽名線位置")]
    public void Renderer_does_not_embed_signature_into_any_of_the_4_signature_lines()
    {
        // Given OwnerSignaturePng = (some PNG bytes)
        var fakePng = new byte[] { 0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A };
        var data = SampleData(fakePng);
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);

        // When
        var html = renderer.Render(data);

        // Then 4 個簽名 <span class="blank wide"> 都不應包含 <img> 或 base64 字串
        var matches = Regex.Matches(html, @"<span class=""blank wide"">([^<]*)</span>");
        matches.Should().HaveCountGreaterThanOrEqualTo(4);
        foreach (Match m in matches)
        {
            var content = m.Groups[1].Value;
            content.Should().NotContain("<img");
            content.Should().NotContain("base64");
        }

        // 整個 HTML 也不應出現 base64 的 img
        html.Should().NotContain("data:image/png;base64,");
    }

    [Fact(DisplayName = "R2 / 既有 GroomingRecord 殘留簽名 Base64 欄位重新產 PDF 時不寫入新值")]
    public void Regenerating_pdf_does_not_write_new_signature_base64()
    {
        // Given GroomingRecord.ContractPaths 已有一個 ContractVersion
        var rec = new GroomingRecord
        {
            GroomingRecordId = "rec_r2_regen",
            ServiceDate = new DateOnly(2026, 5, 16),
            ServiceTime = new TimeOnly(10, 0),
        };
        rec.ContractPaths.Add(new ContractVersion { Version = 1, Path = "/old/path.pdf", GeneratedAt = DateTimeOffset.Now });

        // GroomingRecord entity 中不存在 OwnerSignatureBase64 欄位
        // → reflection 確認無此屬性
        var prop = typeof(GroomingRecord).GetProperty("OwnerSignatureBase64");
        prop.Should().BeNull("GroomingRecord entity 不應存在 OwnerSignatureBase64 屬性（R2 已移除）");

        // ContractPaths 中的 ContractVersion 也不應含此屬性
        var cvProp = typeof(ContractVersion).GetProperty("OwnerSignatureBase64");
        cvProp.Should().BeNull("ContractVersion 不應存在 OwnerSignatureBase64 屬性");
    }

    [Fact(DisplayName = "R2 / GenerateContract 不再以系統內飼主簽名為前置條件")]
    public void GenerateContract_no_longer_requires_owner_signature()
    {
        // PuppeteerSharpContractGenerator.GenerateContractAsync 對任意 OwnerSignaturePng（含 empty）均可執行
        // 確認 ContractTemplateRenderer.Render 在 OwnerSignaturePng 為 empty 時不包含任何「請先完成簽名」之文字
        var data = SampleData(Array.Empty<byte>());
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);

        var html = renderer.Render(data);

        html.Should().NotContain("請先完成飼主簽名");
        html.Should().NotContain("請先完成店家簽名");
        html.Should().NotContain("InvalidOperationException");
    }
}
