// Auto-generated by sa-expert
// Feature: R3 晶片號碼空白時不得自動勾選「未登記 / 無」
// Source: sa/sa-feedback-r3-chip-unregistered-not-inferred.feature
// Architecture: PetService → PetSalonDbContext → SQLite; ContractTemplateRenderer → contract.hbs

using System.Reflection;
using System.Text.RegularExpressions;
using FluentAssertions;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using PetSalon.Core.Abstractions;
using PetSalon.Core.Dtos;
using PetSalon.Core.Entities;
using PetSalon.Core.Services;
using PetSalon.Core.Tests.Helpers;
using PetSalon.Infrastructure.Pdf;
using PetSalon.Infrastructure.Persistence;
using Xunit;

namespace PetSalon.Core.Tests.StepDefinitions;

[Trait("feature", "R3-ChipUnregisteredNotInferred")]
public partial class R3ChipUnregisteredSteps
{
    private readonly string _templatePath;
    private readonly string _fontPath;

    public R3ChipUnregisteredSteps()
    {
        var infraOutput = Path.GetDirectoryName(typeof(PuppeteerSharpContractGenerator).Assembly.Location)!;
        _templatePath = Path.Combine(infraOutput, "Pdf", "Templates", "contract.hbs");
        _fontPath = Path.Combine(infraOutput, "Pdf", "Assets", "kaiu.ttf");
    }

    private static ContractRenderData SampleData(string? chipNumber, string? unregisteredIdMethod)
    {
        var owner = new Owner { OwnerId = "owner_r3", Name = "王小明", NationalId = "A123456789", Phone = "0912345678", Address = "桃園市桃園區慈文路322巷5號" };
        var pet = new Pet
        {
            PetId = "pet_r3", OwnerId = owner.OwnerId, Name = "小白", Species = "犬", Breed = "柴犬", Gender = "公", Age = "3 歲",
            ChipNumber = chipNumber,
            UnregisteredIdMethod = unregisteredIdMethod,
        };
        var appt = new Appointment { AppointmentId = "appt_r3", OwnerId = owner.OwnerId, PetId = pet.PetId, Date = new DateOnly(2026, 5, 16), Time = new TimeOnly(10, 0) };
        var rec = new GroomingRecord { GroomingRecordId = "rec_r3", AppointmentId = appt.AppointmentId, ServiceDate = appt.Date, ServiceTime = appt.Time };
        return new ContractRenderData(owner, pet, appt, rec, Array.Empty<byte>(), "安欣動物醫院", "03-3367775", "桃園市桃園區中福街60號");
    }

    // Helper: find whether the chip/unregistered checkbox near keyword has class "on"
    // The template uses <span class="cb ...on..."> patterns
    // For page1: <span class="cb {{#if pet.unregisteredIdMethod}}on{{/if}}"></span>無
    // For page2: <span class="cb {{#if pet.unregisteredIdMethod}}on{{/if}}"></span>若未登記
    private static bool ChipCheckboxIsOn(string html, string keyword)
    {
        // Find lines containing the keyword and check if the adjacent cb span has class "on"
        var pattern = @"<span class=""cb ([^""]*)""></span>" + Regex.Escape(keyword);
        var m = Regex.Match(html, pattern);
        if (!m.Success) return false;
        return m.Groups[1].Value.Contains("on");
    }

    [Fact(DisplayName = "R3 / ChipNumber 與 UnregisteredIdMethod 皆為 null 時兩處勾選格皆不勾選")]
    public void Both_unchecked_when_chip_and_unregistered_id_method_are_null()
    {
        var data = SampleData(chipNumber: null, unregisteredIdMethod: null);
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);
        var html = renderer.Render(data);

        // page1「無」勾選格不應 .on
        ChipCheckboxIsOn(html, "無").Should().BeFalse("ChipNumber=null, UnregisteredIdMethod=null → 「無」不勾");
        // page2「若未登記」勾選格不應 .on
        ChipCheckboxIsOn(html, "若未登記").Should().BeFalse("ChipNumber=null, UnregisteredIdMethod=null → 「若未登記」不勾");
        // 晶片號碼儲存格應為空
        html.Should().MatchRegex(@"<td class=""label"">晶片號碼</td>\s*<td class=""val""></td>");
    }

    [Fact(DisplayName = "R3 / ChipNumber=null 但 UnregisteredIdMethod 有值時兩處勾選格皆勾選")]
    public void Both_checked_when_chip_null_but_unregistered_id_method_has_value()
    {
        var data = SampleData(chipNumber: null, unregisteredIdMethod: "項圈牌號 A12");
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);
        var html = renderer.Render(data);

        html.Should().Contain("項圈牌號 A12");
        // page1「無」勾選格應 .on
        ChipCheckboxIsOn(html, "無").Should().BeTrue("UnregisteredIdMethod 有值 → 「無」應勾");
        // page2「若未登記」勾選格應 .on
        ChipCheckboxIsOn(html, "若未登記").Should().BeTrue("UnregisteredIdMethod 有值 → 「若未登記」應勾");
    }

    [Fact(DisplayName = "R3 / ChipNumber 有值且 UnregisteredIdMethod=null 時兩處勾選格皆不勾選")]
    public void Both_unchecked_when_chip_has_value_and_unregistered_id_method_is_null()
    {
        var data = SampleData(chipNumber: "900123456789012", unregisteredIdMethod: null);
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);
        var html = renderer.Render(data);

        html.Should().Contain("900123456789012");
        // 兩處皆不勾
        ChipCheckboxIsOn(html, "無").Should().BeFalse();
        ChipCheckboxIsOn(html, "若未登記").Should().BeFalse();
    }

    [Fact(DisplayName = "R3 / ChipNumber 與 UnregisteredIdMethod 皆有值時以 UnregisteredIdMethod 為勾選依據")]
    public void Both_checked_when_both_chip_and_unregistered_id_method_have_value()
    {
        var data = SampleData(chipNumber: "900123456789012", unregisteredIdMethod: "舊晶片損壞，已換項圈牌號 B05");
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);
        var html = renderer.Render(data);

        html.Should().Contain("900123456789012");
        html.Should().Contain("舊晶片損壞，已換項圈牌號 B05");
        // UnregisteredIdMethod 有值 → 兩處皆勾
        ChipCheckboxIsOn(html, "無").Should().BeTrue();
        ChipCheckboxIsOn(html, "若未登記").Should().BeTrue();
    }

    [Fact(DisplayName = "R3 / 不新增任何專用布林欄位至 Pet entity")]
    public void Pet_entity_has_no_IsUnregistered_property()
    {
        // When
        var props = typeof(Pet).GetProperties(BindingFlags.Public | BindingFlags.Instance);

        // Then
        props.Should().NotContain(p => p.Name == "IsUnregistered");
        props.Should().Contain(p => p.Name == "ChipNumber" && p.PropertyType == typeof(string));
        props.Should().Contain(p => p.Name == "UnregisteredIdMethod" && p.PropertyType == typeof(string));
    }

    [Fact(DisplayName = "R3 / PetService.SaveAsync 對 ChipNumber=null 之 Pet 不應拋例外")]
    public async Task PetService_SaveAsync_with_null_chip_does_not_throw()
    {
        var connection = new SqliteConnection("DataSource=:memory:");
        connection.Open();
        var options = new DbContextOptionsBuilder<PetSalonDbContext>()
            .UseSqlite(connection)
            .Options;
        await using var db = new PetSalonDbContext(options);
        db.Database.EnsureCreated();

        var ids = new SequentialIdGenerator();
        var clock = new FakeClock();
        var ownerSvc = new OwnerService(db, ids, clock);
        var petSvc = new PetService(db, ids, clock);

        // 先建立 owner
        var owner = await ownerSvc.CreateAsync(new OwnerInput
        {
            Name = "王小明",
            NationalId = "A123456789",
            Phone = "0912345678",
            Address = "桃園市桃園區慈文路322巷5號",
        });

        // Given Pet ChipNumber=null, UnregisteredIdMethod=null
        var input = new PetInput
        {
            OwnerId = owner.OwnerId,
            Name = "小白",
            Species = "犬",
            Breed = "柴犬",
            Gender = "公",
            Age = "3 歲",
            Personality = new List<string> { "親人" },
            ChipNumber = null,
            UnregisteredIdMethod = null,
            PhysicalExamination = new PhysicalExamination(),
        };

        // When / Then 不應拋例外
        var pet = await petSvc.CreateAsync(input);
        pet.ChipNumber.Should().BeNull();
        pet.UnregisteredIdMethod.Should().BeNull();

        // And SQLite 中應為 NULL
        var loaded = await petSvc.GetByIdAsync(pet.PetId);
        loaded.ChipNumber.Should().BeNull();
        loaded.UnregisteredIdMethod.Should().BeNull();

        await connection.CloseAsync();
        connection.Dispose();
    }

    [Theory(DisplayName = "R3 / Scenario Outline：不同晶片組合下勾選格行為")]
    [InlineData(null, null, false, false)]
    [InlineData(null, "無", true, true)]
    [InlineData(null, "項圈牌號 A12", true, true)]
    [InlineData("900123456789012", null, false, false)]
    [InlineData("900123456789012", "舊晶片損壞已換項圈", true, true)]
    public void Outline_chip_combinations(string? chipNumber, string? unregisteredIdMethod, bool page1Checked, bool page4Checked)
    {
        var data = SampleData(chipNumber, unregisteredIdMethod);
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);
        var html = renderer.Render(data);

        // page1「無」勾選格
        ChipCheckboxIsOn(html, "無").Should().Be(page1Checked,
            $"chip={chipNumber}, method={unregisteredIdMethod} → page1 checked should be {page1Checked}");
        // page2「若未登記」勾選格
        ChipCheckboxIsOn(html, "若未登記").Should().Be(page4Checked,
            $"chip={chipNumber}, method={unregisteredIdMethod} → page2 checked should be {page4Checked}");
    }
}
