// Auto-generated by sa-expert
// Feature: R5 簽名欄不得自動帶入姓名（含 Q2 乙方亦空白）
// Source: sa/sa-feedback-r5-signature-lines-blank.feature
// Architecture: contract.hbs 第 239 / 240 / 432 行字串替換

using System.Text.RegularExpressions;
using FluentAssertions;
using PetSalon.Core.Abstractions;
using PetSalon.Core.Entities;
using PetSalon.Infrastructure.Pdf;
using Xunit;

namespace PetSalon.Core.Tests.StepDefinitions;

[Trait("feature", "R5-SignatureLinesBlank")]
public partial class R5SignatureBlankSteps
{
    private readonly string _templatePath;
    private readonly string _fontPath;

    public R5SignatureBlankSteps()
    {
        var infraOutput = Path.GetDirectoryName(typeof(PuppeteerSharpContractGenerator).Assembly.Location)!;
        _templatePath = Path.Combine(infraOutput, "Pdf", "Templates", "contract.hbs");
        _fontPath = Path.Combine(infraOutput, "Pdf", "Assets", "kaiu.ttf");
    }

    private static ContractRenderData SampleData(string ownerName = "王小明")
    {
        var owner = new Owner { OwnerId = "owner_r5", Name = ownerName, NationalId = "A123456789", Phone = "0912345678", Address = "桃園市桃園區慈文路322巷5號" };
        var pet = new Pet { PetId = "pet_r5", OwnerId = owner.OwnerId, Name = "小白", Species = "犬", Breed = "柴犬", Gender = "公", Age = "3 歲" };
        var appt = new Appointment { AppointmentId = "appt_r5", OwnerId = owner.OwnerId, PetId = pet.PetId, Date = new DateOnly(2026, 5, 16), Time = new TimeOnly(10, 0) };
        var rec = new GroomingRecord { GroomingRecordId = "rec_r5", AppointmentId = appt.AppointmentId, ServiceDate = appt.Date, ServiceTime = appt.Time };
        return new ContractRenderData(owner, pet, appt, rec, Array.Empty<byte>(), "安欣動物醫院", "03-3367775", "桃園市桃園區中福街60號");
    }

    // 從 HTML 提取緊接在某個標籤後的 <span class="blank wide"> 內容
    private static string ExtractBlankWideContent(string html, string labelPrefix)
    {
        var pattern = Regex.Escape(labelPrefix) + @"：<span class=""blank wide"">([^<]*)</span>";
        var m = Regex.Match(html, pattern);
        return m.Success ? m.Groups[1].Value : string.Empty;
    }

    [Fact(DisplayName = "R5 / 甲方簽章線不應帶入 Owner.Name")]
    public void Party_A_signature_line_does_not_contain_owner_name()
    {
        // Given
        var data = SampleData("王小明");
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);

        // When
        var html = renderer.Render(data);

        // Then 甲方簽章 span 應為空白
        var partyAContent = ExtractBlankWideContent(html, "甲方簽章");
        partyAContent.Trim().Should().BeEmpty("甲方簽章 <span class=\"blank wide\"> 不應含 Owner.Name");
        html.Should().NotContain("甲方簽章：<span class=\"blank wide\">王小明</span>");
    }

    [Fact(DisplayName = "R5 / 乙方簽章線不應帶入「貳寶寵物美容工坊」字樣（Q2）")]
    public void Party_B_signature_line_does_not_contain_shop_name()
    {
        var data = SampleData();
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);
        var html = renderer.Render(data);

        // Then 乙方簽章 span 應為空白
        var partyBContent = ExtractBlankWideContent(html, "乙方簽章");
        partyBContent.Trim().Should().BeEmpty("乙方簽章 <span class=\"blank wide\"> 不應含「貳寶寵物美容工坊」");
        html.Should().NotContain("乙方簽章：<span class=\"blank wide\">貳寶寵物美容工坊</span>");
    }

    [Fact(DisplayName = "R5 / 飼主簽名線不應帶入 Owner.Name")]
    public void Owner_signature_line_does_not_contain_owner_name()
    {
        var data = SampleData("王小明");
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);
        var html = renderer.Render(data);

        // Then 飼主簽名 span 應為空白
        var ownerSigContent = ExtractBlankWideContent(html, "飼主簽名");
        ownerSigContent.Trim().Should().BeEmpty("飼主簽名 <span class=\"blank wide\"> 不應含 Owner.Name");
        html.Should().NotContain("飼主簽名：<span class=\"blank wide\">王小明</span>");
    }

    [Fact(DisplayName = "R5 / 美容人員簽名線維持空白")]
    public void Groomer_signature_line_remains_blank()
    {
        var data = SampleData();
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);
        var html = renderer.Render(data);

        // Then 美容人員簽名 span 應為空白且不含樣板殘留
        var groomerSigContent = ExtractBlankWideContent(html, "美容人員簽名");
        groomerSigContent.Trim().Should().BeEmpty("美容人員簽名 <span class=\"blank wide\"> 應為空白");
        html.Should().NotContain("{{");  // 不應有 Handlebars 殘留
    }

    [Fact(DisplayName = "R5 / contract.hbs 甲方簽章所在行不應包含 {{owner.name}}")]
    public void Hbs_line_239_does_not_contain_owner_name_variable()
    {
        // When
        var lines = File.ReadAllLines(_templatePath);

        // R4 頁面重排後，原 spec 中「第 239 行」之絕對行號已移位。
        // 改為行為層級：搜尋含「甲方簽章」的那行，斷言不含 {{owner.name}}。
        var partyALine = lines.FirstOrDefault(l => l.Contains("甲方簽章"));
        partyALine.Should().NotBeNull("contract.hbs 應含「甲方簽章」之行");
        partyALine.Should().NotContain("{{owner.name}}");
    }

    [Fact(DisplayName = "R5 / contract.hbs 乙方簽章所在行不應包含「貳寶寵物美容工坊」字樣")]
    public void Hbs_line_240_does_not_contain_shop_name_literal()
    {
        var lines = File.ReadAllLines(_templatePath);
        // R4 頁面重排後行號已移位，改為行為層級
        var partyBLine = lines.FirstOrDefault(l => l.Contains("乙方簽章"));
        partyBLine.Should().NotBeNull("contract.hbs 應含「乙方簽章」之行");
        partyBLine.Should().NotContain("貳寶寵物美容工坊");
    }

    [Fact(DisplayName = "R5 / contract.hbs 飼主簽名所在行不應包含 {{owner.name}}")]
    public void Hbs_line_432_does_not_contain_owner_name_variable()
    {
        var lines = File.ReadAllLines(_templatePath);
        // R4 頁面重排後行號已移位，改為行為層級
        var ownerSigLine = lines.FirstOrDefault(l => l.Contains("飼主簽名"));
        ownerSigLine.Should().NotBeNull("contract.hbs 應含「飼主簽名」之行");
        ownerSigLine.Should().NotContain("{{owner.name}}");
    }

    [Fact(DisplayName = "R5 / 4 個簽名線 CSS .blank.wide 維持 min-width 50mm")]
    public void Css_blank_wide_min_width_preserved()
    {
        var source = File.ReadAllText(_templatePath);
        source.Should().Contain(".blank.wide { min-width: 50mm; }");
    }

    [Fact(DisplayName = "R5 / 簽名日期維持系統帶入今日民國年月日")]
    public void Signature_date_filled_from_system_today()
    {
        // Given ServiceDate = 2026-05-16
        var data = SampleData();
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);
        var html = renderer.Render(data);

        // Then HTML 應出現 "中華民國" 與 民國 115 / 5 / 16
        html.Should().Contain("中華民國");
        // 用 regex 取出 rocYear / rocMonth / rocDay
        var yearMatch = Regex.Match(html, @"中華民國.*?<span class=""blank"">(\d+)</span>\s*年", RegexOptions.Singleline);
        if (yearMatch.Success)
            yearMatch.Groups[1].Value.Should().Be("115", "民國年 = 2026 - 1911 = 115");
    }

    [Theory(DisplayName = "R5 / 不同飼主姓名下 4 個簽名線皆空白")]
    [InlineData("王小明")]
    [InlineData("林大華")]
    [InlineData("陳美麗")]
    public void All_4_signature_lines_blank_for_any_owner_name(string ownerName)
    {
        var data = SampleData(ownerName);
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);
        var html = renderer.Render(data);

        // 甲方 / 飼主 簽名線不應出現 ownerName 在 .blank.wide 內
        html.Should().NotContain($"甲方簽章：<span class=\"blank wide\">{ownerName}</span>");
        html.Should().NotContain($"飼主簽名：<span class=\"blank wide\">{ownerName}</span>");
        // 乙方 / 美容人員 簽名線 span 應為空白
        ExtractBlankWideContent(html, "乙方簽章").Trim().Should().BeEmpty();
        ExtractBlankWideContent(html, "美容人員簽名").Trim().Should().BeEmpty();
    }
}
