// Auto-generated by sa-expert
// Feature: R7 寵物病史新增「以上皆無」選項（含 Q6 空陣列視為以上皆無）
// Source: sa/sa-feedback-r7-medical-history-none-of-above.feature
// Architecture: MedicalHistoryOptions 常數擴充；contract.hbs 第 377–406 行新增「以上皆無」勾選格

using System.Text.RegularExpressions;
using FluentAssertions;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using PetSalon.Core.Abstractions;
using PetSalon.Core.Constants;
using PetSalon.Core.Dtos;
using PetSalon.Core.Entities;
using PetSalon.Core.Services;
using PetSalon.Core.Tests.Helpers;
using PetSalon.Infrastructure.Pdf;
using PetSalon.Infrastructure.Persistence;
using Xunit;

namespace PetSalon.Core.Tests.StepDefinitions;

[Trait("feature", "R7-MedicalHistoryNoneOfAbove")]
public partial class R7MedicalHistorySteps
{
    private readonly string _templatePath;
    private readonly string _fontPath;

    public R7MedicalHistorySteps()
    {
        var infraOutput = Path.GetDirectoryName(typeof(PuppeteerSharpContractGenerator).Assembly.Location)!;
        _templatePath = Path.Combine(infraOutput, "Pdf", "Templates", "contract.hbs");
        _fontPath = Path.Combine(infraOutput, "Pdf", "Assets", "kaiu.ttf");
    }

    private static ContractRenderData SampleData(List<string>? medicalHistory = null)
    {
        var owner = new Owner { OwnerId = "owner_r7", Name = "王小明", NationalId = "A123456789", Phone = "0912345678", Address = "桃園市桃園區慈文路322巷5號" };
        var pet = new Pet { PetId = "pet_r7", OwnerId = owner.OwnerId, Name = "小白", Species = "犬", Breed = "柴犬", Gender = "公", Age = "3 歲" };
        var appt = new Appointment { AppointmentId = "appt_r7", OwnerId = owner.OwnerId, PetId = pet.PetId, Date = new DateOnly(2026, 5, 16), Time = new TimeOnly(10, 0) };
        var rec = new GroomingRecord
        {
            GroomingRecordId = "rec_r7", AppointmentId = appt.AppointmentId,
            ServiceDate = appt.Date, ServiceTime = appt.Time,
            MedicalHistory = medicalHistory ?? new List<string>(),
        };
        return new ContractRenderData(owner, pet, appt, rec, Array.Empty<byte>(), "安欣動物醫院", "03-3367775", "桃園市桃園區中福街60號");
    }

    // Helper: check if 以上皆無 checkbox has class "on" in the rendered HTML
    private static bool NoneOfAboveIsOn(string html)
    {
        // <span class="cb on"></span>以上皆無  or  <span class="cb "></span>以上皆無
        var m = Regex.Match(html, @"<span class=""cb ([^""]*)""></span>以上皆無");
        return m.Success && m.Groups[1].Value.Contains("on");
    }

    // Helper: check if a specific disease checkbox has class "on"
    private static bool DiseaseIsOn(string html, string disease)
    {
        var pattern = @"<span class=""cb ([^""]*)""></span>" + Regex.Escape(disease);
        var m = Regex.Match(html, pattern);
        return m.Success && m.Groups[1].Value.Contains("on");
    }

    [Fact(DisplayName = "R7 / MedicalHistoryOptions.All 擴充為 19 項且「以上皆無」位於末尾")]
    public void MedicalHistoryOptions_has_19_items_with_none_of_above_at_end()
    {
        // When
        var all = MedicalHistoryOptions.All;

        // Then
        all.Count.Should().Be(19);
        all[18].Should().Be("以上皆無");
    }

    [Fact(DisplayName = "R7 / 前 18 項順序與字串內容皆不變")]
    public void First_18_items_unchanged()
    {
        var expectedFirst18 = new[]
        {
            "心臟病", "氣喘", "氣管塌陷", "癲癇",
            "白內障", "心絲蟲", "艾利希體",
            "腸炎", "腹膜炎", "腹積水",
            "血便", "血尿", "骨折", "髖關節問題",
            "懷孕", "手術外傷未癒合",
            "傳染性疾病", "其它",
        };
        for (int i = 0; i < expectedFirst18.Length; i++)
        {
            MedicalHistoryOptions.All[i].Should().Be(expectedFirst18[i], $"index {i} 不應變更");
        }
    }

    [Fact(DisplayName = "R7 / IsValid(\"以上皆無\") 應回傳 true")]
    public void IsValid_none_of_above_returns_true()
    {
        MedicalHistoryOptions.IsValid("以上皆無").Should().BeTrue();
    }

    [Fact(DisplayName = "R7 / 後端 PetService 不對 MedicalHistory 內容組合執行額外驗證")]
    public async Task PetService_does_not_validate_medical_history_combinations()
    {
        var connection = new SqliteConnection("DataSource=:memory:");
        connection.Open();
        var options = new DbContextOptionsBuilder<PetSalonDbContext>()
            .UseSqlite(connection)
            .Options;
        await using var db = new PetSalonDbContext(options);
        db.Database.EnsureCreated();

        var ids = new SequentialIdGenerator();
        var clock = new FakeClock();
        var ownerSvc = new OwnerService(db, ids, clock);
        var petSvc = new PetService(db, ids, clock);

        var owner = await ownerSvc.CreateAsync(new OwnerInput
        {
            Name = "王小明", NationalId = "A123456789", Phone = "0912345678", Address = "桃園市桃園區慈文路322巷5號"
        });

        // Given Pet.MedicalHistory = ["以上皆無", "心臟病"]（語意衝突但合法字串）
        var input = new PetInput
        {
            OwnerId = owner.OwnerId, Name = "小白", Species = "犬", Breed = "柴犬", Gender = "公", Age = "3 歲",
            Personality = new List<string> { "親人" },
            MedicalHistory = new List<string> { "以上皆無", "心臟病" },
            PhysicalExamination = new PhysicalExamination(),
        };

        // When 呼叫 PetService.CreateAsync
        var pet = await petSvc.CreateAsync(input);

        // Then 不應拋例外；MedicalHistory 儲存兩個值
        pet.MedicalHistory.Should().Contain("以上皆無");
        pet.MedicalHistory.Should().Contain("心臟病");

        await connection.CloseAsync();
        connection.Dispose();
    }

    [Fact(DisplayName = "R7 / PDF 寵物病史區塊新增「以上皆無」勾選格")]
    public void Pdf_medical_history_block_has_none_of_above_checkbox()
    {
        var data = SampleData(new List<string> { "以上皆無" });
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);
        var html = renderer.Render(data);

        html.Should().Contain("以上皆無", "HTML 應包含「以上皆無」文字");
        // 確認存在對應的 <span class="cb"> 元素
        html.Should().MatchRegex(@"<span class=""cb[^""]*""></span>以上皆無", "應有勾選格對應「以上皆無」");
    }

    [Fact(DisplayName = "R7 / MedicalHistory 包含「以上皆無」時 HTML 勾選「以上皆無」")]
    public void Html_checks_none_of_above_when_list_contains_it()
    {
        var data = SampleData(new List<string> { "以上皆無" });
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);
        var html = renderer.Render(data);

        NoneOfAboveIsOn(html).Should().BeTrue("MedicalHistory=['以上皆無'] → 以上皆無應勾選");
        // 其他病史不應勾選
        DiseaseIsOn(html, "心臟病").Should().BeFalse();
        DiseaseIsOn(html, "氣喘").Should().BeFalse();
    }

    [Fact(DisplayName = "R7/Q6 / MedicalHistory 為空陣列時 HTML 自動勾選「以上皆無」")]
    public void Html_auto_checks_none_of_above_when_list_is_empty()
    {
        var data = SampleData(new List<string>());
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);
        var html = renderer.Render(data);

        NoneOfAboveIsOn(html).Should().BeTrue("MedicalHistory=[] → 以上皆無應自動勾選");
    }

    [Fact(DisplayName = "R7 / MedicalHistory 包含具體病史時 HTML 不勾選「以上皆無」")]
    public void Html_does_not_check_none_of_above_when_specific_diseases_present()
    {
        var data = SampleData(new List<string> { "心臟病", "氣喘" });
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);
        var html = renderer.Render(data);

        DiseaseIsOn(html, "心臟病").Should().BeTrue("心臟病應勾選");
        DiseaseIsOn(html, "氣喘").Should().BeTrue("氣喘應勾選");
        NoneOfAboveIsOn(html).Should().BeFalse("有具體病史時以上皆無不應勾選");
    }

    [Fact(DisplayName = "R7 / 既有 SQLite 中 MedicalHistory=[] 之 Pet 不需 migration 且 PDF 自動勾選")]
    public async Task Existing_pets_with_empty_medical_history_do_not_need_migration()
    {
        var connection = new SqliteConnection("DataSource=:memory:");
        connection.Open();
        var options = new DbContextOptionsBuilder<PetSalonDbContext>()
            .UseSqlite(connection)
            .Options;
        await using var db = new PetSalonDbContext(options);
        db.Database.EnsureCreated();

        var ids = new SequentialIdGenerator();
        var clock = new FakeClock();
        var ownerSvc = new OwnerService(db, ids, clock);
        var petSvc = new PetService(db, ids, clock);

        var owner = await ownerSvc.CreateAsync(new OwnerInput
        {
            Name = "王小明", NationalId = "A123456789", Phone = "0912345678", Address = "桃園市桃園區慈文路322巷5號"
        });

        // 建立 MedicalHistory=[] 的 Pet
        var input = new PetInput
        {
            OwnerId = owner.OwnerId, Name = "小白", Species = "犬", Breed = "柴犬", Gender = "公", Age = "3 歲",
            Personality = new List<string> { "親人" },
            MedicalHistory = new List<string>(),
            PhysicalExamination = new PhysicalExamination(),
        };
        var pet = await petSvc.CreateAsync(input);

        // 重新載入
        var loaded = await petSvc.GetByIdAsync(pet.PetId);
        loaded.MedicalHistory.Should().BeEmpty("MedicalHistory 應為空 List<string>");

        // 後續 PDF 渲染時「以上皆無」應自動勾選
        var appt = new Appointment { AppointmentId = "appt_r7b", OwnerId = owner.OwnerId, PetId = loaded.PetId, Date = new DateOnly(2026, 5, 16), Time = new TimeOnly(10, 0) };
        var rec = new GroomingRecord { GroomingRecordId = "rec_r7b", AppointmentId = appt.AppointmentId, ServiceDate = appt.Date, ServiceTime = appt.Time, MedicalHistory = new List<string>() };
        var renderData = new ContractRenderData(owner, loaded, appt, rec, Array.Empty<byte>(), "安欣動物醫院", "03-3367775", "桃園市桃園區中福街60號");

        var infraOutput = Path.GetDirectoryName(typeof(PuppeteerSharpContractGenerator).Assembly.Location)!;
        var templatePath = Path.Combine(infraOutput, "Pdf", "Templates", "contract.hbs");
        var fontPath = Path.Combine(infraOutput, "Pdf", "Assets", "kaiu.ttf");
        var renderer = new ContractTemplateRenderer(templatePath, fontPath);
        var html = renderer.Render(renderData);

        NoneOfAboveIsOn(html).Should().BeTrue("MedicalHistory=[] → PDF 以上皆無應勾選");

        await connection.CloseAsync();
        connection.Dispose();
    }

    [Theory(DisplayName = "R7 / Scenario Outline：MedicalHistory 不同輸入下「以上皆無」之勾選")]
    [InlineData(new string[0], true)]
    [InlineData(new[] { "以上皆無" }, true)]
    [InlineData(new[] { "心臟病" }, false)]
    [InlineData(new[] { "其它" }, false)]
    [InlineData(new[] { "心臟病", "氣喘" }, false)]
    public void Outline_none_of_above_check_state(string[] history, bool expectedChecked)
    {
        var data = SampleData(history.ToList());
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);
        var html = renderer.Render(data);

        NoneOfAboveIsOn(html).Should().Be(expectedChecked,
            $"MedicalHistory=[{string.Join(",", history)}] → 以上皆無 checked should be {expectedChecked}");
    }
}
