// Auto-generated by sa-expert
// Feature: R8 PDF 條款短版文字改用客戶提供原文（含 Q4 修正）
// Source: sa/sa-feedback-r8-contract-clauses-text.feature
// Architecture: contract.hbs 第 413–425 行 ＊段 + <ol> 全段替換

using FluentAssertions;
using PetSalon.Core.Abstractions;
using PetSalon.Core.Entities;
using PetSalon.Infrastructure.Pdf;
using Xunit;

namespace PetSalon.Core.Tests.StepDefinitions;

[Trait("feature", "R8-ContractClausesText")]
public partial class R8ContractClausesSteps
{
    private readonly string _templatePath;
    private readonly string _fontPath;

    public R8ContractClausesSteps()
    {
        var infraOutput = Path.GetDirectoryName(typeof(PuppeteerSharpContractGenerator).Assembly.Location)!;
        _templatePath = Path.Combine(infraOutput, "Pdf", "Templates", "contract.hbs");
        _fontPath = Path.Combine(infraOutput, "Pdf", "Assets", "kaiu.ttf");
    }

    private static ContractRenderData SampleData()
    {
        var owner = new Owner { OwnerId = "owner_r8", Name = "王小明", NationalId = "A123456789", Phone = "0912345678", Address = "桃園市桃園區慈文路322巷5號" };
        var pet = new Pet { PetId = "pet_r8", OwnerId = owner.OwnerId, Name = "小白", Species = "犬", Breed = "柴犬", Gender = "公", Age = "3 歲" };
        var appt = new Appointment { AppointmentId = "appt_r8", OwnerId = owner.OwnerId, PetId = pet.PetId, Date = new DateOnly(2026, 5, 16), Time = new TimeOnly(10, 0) };
        var rec = new GroomingRecord { GroomingRecordId = "rec_r8", AppointmentId = appt.AppointmentId, ServiceDate = appt.Date, ServiceTime = appt.Time };
        return new ContractRenderData(owner, pet, appt, rec, Array.Empty<byte>(), "安欣動物醫院", "03-3367775", "桃園市桃園區中福街60號");
    }

    private const string ExpectedAsteriskParagraph =
        "＊以上資料由飼主本人提供，並同意將資料內容提供於公司存續期間以電話、簡訊和寄發DM方式，提供相關活動或促銷訊息、或帶寵物到動物醫院留存相關資料使用。";

    private static readonly string[] Expected8Clauses = new[]
    {
        "除本契約另有約定、特殊緊急情況、或不可抗力之情況外，未經飼主同意，店家不得將寵物帶離美容場所（同上店家地址）、轉售、轉讓或以其他變相方法作為其他用途。",
        "飼主應於美容當日，將寵物領回，如經通知1日內未領回，依動保法第29條第一款通知主管機關，視為飼主惡意棄養，相關罰金為3萬~15萬元，其他衍生性費用將跟飼主求償，例：人員加班費等。",
        "寵物發生攻擊行為，如因飼主未普盡告知義務而造成店內人員傷亡、財物毀損等費用，將全額向飼主（寵物占有權人）求償。",
        "店家應按本契約約定內容提供一定品質之美容服務。若因可歸責於店家或其受僱人之事由，導致其提供之美容服務有瑕疵，造成飼主發生損失的情況，飼主得要求減少價金或解除契約。",
        "本契約之任一方得隨時終止本契約，若因本契約之終止而生損害之一方得向他方請求賠償。",
        "於美容服務期間，如發現寵物有異常狀態，應立即通知飼主並妥善處理，如發生異常狀態的原因，可歸責店家之操作行為，店家應負損害賠償責任，例：摔傷寵物等。",
        "因本契約所生之訴訟，雙方合意以 地方法院為管轄法院。",
        "其他：",
    };

    [Fact(DisplayName = "R8 / ＊段同意文字逐字符合客戶原文")]
    public void Asterisk_paragraph_matches_client_text()
    {
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);
        var html = renderer.Render(SampleData());

        html.Should().Contain(ExpectedAsteriskParagraph);
    }

    [Fact(DisplayName = "R8 / <ol> 應包含正好 8 個 <li>")]
    public void Ol_contains_exactly_8_li_items()
    {
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);
        var html = renderer.Render(SampleData());

        // TODO: 用 regex 抽出 contract.hbs 第 413–425 行附近的 <ol>...</ol>，數 <li> 數量
        var liItems = ExtractLiItems(html);
        liItems.Should().HaveCount(8);
    }

    [Fact(DisplayName = "R8 / 條款第 1 點原文逐字符合")]
    public void Clause_1_matches()
    {
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);
        var html = renderer.Render(SampleData());
        var liItems = ExtractLiItems(html);

        liItems[0].Should().Be(Expected8Clauses[0]);
    }

    [Fact(DisplayName = "R8/Q4 / 條款第 2 點原文已修正為「視為飼主惡意棄養」")]
    public void Clause_2_corrected_with_q4_fix()
    {
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);
        var html = renderer.Render(SampleData());
        var liItems = ExtractLiItems(html);

        liItems[1].Should().Be(Expected8Clauses[1]);
        liItems[1].Should().Contain("視為飼主惡意棄養");
        liItems[1].Should().NotContain("為飼主惡意養");  // 舊錯字版本
    }

    [Fact(DisplayName = "R8 / 條款第 3 點原文逐字符合")]
    public void Clause_3_matches()
    {
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);
        var liItems = ExtractLiItems(renderer.Render(SampleData()));
        liItems[2].Should().Be(Expected8Clauses[2]);
    }

    [Fact(DisplayName = "R8 / 條款第 4 點原文逐字符合")]
    public void Clause_4_matches()
    {
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);
        var liItems = ExtractLiItems(renderer.Render(SampleData()));
        liItems[3].Should().Be(Expected8Clauses[3]);
    }

    [Fact(DisplayName = "R8 / 條款第 5 點原文逐字符合")]
    public void Clause_5_matches()
    {
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);
        var liItems = ExtractLiItems(renderer.Render(SampleData()));
        liItems[4].Should().Be(Expected8Clauses[4]);
    }

    [Fact(DisplayName = "R8 / 條款第 6 點原文逐字符合")]
    public void Clause_6_matches()
    {
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);
        var liItems = ExtractLiItems(renderer.Render(SampleData()));
        liItems[5].Should().Be(Expected8Clauses[5]);
    }

    [Fact(DisplayName = "R8 / 條款第 7 點保留「以 地方法院」之半形空格")]
    public void Clause_7_preserves_halfwidth_space()
    {
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);
        var liItems = ExtractLiItems(renderer.Render(SampleData()));
        liItems[6].Should().Be(Expected8Clauses[6]);
        liItems[6].Should().Contain("以 地方法院");  // 注意「以」與「地方法院」之間有 1 個半形空格
    }

    [Fact(DisplayName = "R8 / 條款第 8 點以「其他：」開頭，且包含可手寫之長底線")]
    public void Clause_8_starts_with_other_colon_with_long_underline()
    {
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);
        var html = renderer.Render(SampleData());
        // 從 raw HTML 檢查：<li> 以「其他：」開頭，且含 .blank.xwide 或 _ 底線
        html.Should().MatchRegex(@"<li>其他：(<span class=""blank xwide""></span>|_{8,})</li>",
            "第 8 點應以「其他：」開頭並含可手寫長底線（.blank.xwide span 或 _ 字元）");
        var liItems = ExtractLiItems(html);
        liItems.Should().HaveCountGreaterThanOrEqualTo(8);
        liItems[7].Should().StartWith("其他：");
    }

    [Fact(DisplayName = "R8 / ＊段位置應位於 1~8 點條款之前")]
    public void Asterisk_paragraph_appears_before_ol()
    {
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);
        var html = renderer.Render(SampleData());

        var asteriskIdx = html.IndexOf(ExpectedAsteriskParagraph, StringComparison.Ordinal);
        var olIdx = html.IndexOf("<ol", StringComparison.Ordinal);
        asteriskIdx.Should().BeGreaterThan(-1);
        olIdx.Should().BeGreaterThan(-1);
        asteriskIdx.Should().BeLessThan(olIdx);
    }

    [Fact(DisplayName = "R8 / 不應出現舊模板殘留錯字")]
    public void Should_not_contain_old_broken_texts()
    {
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);
        var html = renderer.Render(SampleData());

        html.Should().NotContain("基本契約同付屬定");
        html.Should().NotContain("寵主進店美容契約書");
        html.Should().NotContain("店家得基於契約所涉可歸責甲方");
        html.Should().NotContain("為飼主惡意養");  // Q4 舊錯字
    }

    [Theory(DisplayName = "R8 / Scenario Outline：8 點條款逐點檢查關鍵字")]
    [InlineData(1, "不得將寵物帶離")]
    [InlineData(2, "視為飼主惡意棄養")]
    [InlineData(3, "寵物占有權人")]
    [InlineData(4, "一定品質之美容服務")]
    [InlineData(5, "任一方得隨時終止")]
    [InlineData(6, "摔傷寵物")]
    [InlineData(7, "以 地方法院")]
    [InlineData(8, "其他：")]
    public void Outline_each_clause_contains_keyword(int clauseNumber, string keyword)
    {
        var renderer = new ContractTemplateRenderer(_templatePath, _fontPath);
        var liItems = ExtractLiItems(renderer.Render(SampleData()));
        liItems.Should().HaveCount(8);
        liItems[clauseNumber - 1].Should().Contain(keyword);
    }

    // ===== Helper =====
    private static List<string> ExtractLiItems(string html)
    {
        // 提取 <ol> 內 <li> 的純文字（移除 HTML 標籤）
        var olStart = html.IndexOf("<ol", StringComparison.Ordinal);
        if (olStart < 0) return new List<string>();
        var olEnd = html.IndexOf("</ol>", olStart, StringComparison.Ordinal);
        if (olEnd < 0) return new List<string>();
        var ol = html.Substring(olStart, olEnd - olStart);

        var items = new List<string>();
        var liStart = 0;
        while (true)
        {
            liStart = ol.IndexOf("<li", liStart, StringComparison.Ordinal);
            if (liStart < 0) break;
            var liContentStart = ol.IndexOf('>', liStart) + 1;
            var liEnd = ol.IndexOf("</li>", liContentStart, StringComparison.Ordinal);
            if (liEnd < 0) break;
            var rawContent = ol.Substring(liContentStart, liEnd - liContentStart).Trim();
            // 移除 HTML 標籤，但保留純文字（第 8 點的 span 為空，去掉後只剩「其他：」）
            var textContent = System.Text.RegularExpressions.Regex.Replace(rawContent, @"<[^>]+>", string.Empty).Trim();
            items.Add(textContent);
            liStart = liEnd + "</li>".Length;
        }
        return items;
    }
}
