// Auto-generated by sa-expert + Phase 4 implementation
// Feature: R1 緊急聯絡人欄位取消必填（UI 場景）
// Source: sa/sa-feedback-r1-emergency-contact-optional.feature（@ui Scenarios）
// Module type: WPF UI E2E（FlaUI.UIA3 + xUnit v3）
//
// 注意：SA spec 中使用 nav-owner，但實際 AutomationId 為 nav-owners（複數）。
// Phase 3 agent 已記錄此 typo，此處改為正確的 nav-owners。

using FluentAssertions;
using PetSalon.Wpf.UiTests.Helpers;
using Xunit;

namespace PetSalon.Wpf.UiTests.StepDefinitions;

[Trait("category", "ui")]
[Trait("feature", "R1-EmergencyContactOptional")]
[Collection("uiseq")]
public partial class R1EmergencyContactUiSteps : IClassFixture<AppFixture>
{
    private readonly AppFixture _fx;

    public R1EmergencyContactUiSteps(AppFixture fx)
    {
        _fx = fx;
        // SA spec 用 nav-owner，實際 AutomationId 為 nav-owners
        _fx.ClickById("nav-owners");
    }

    [Fact(DisplayName = "R1 / OwnerPageView 三欄不顯示必填紅星或必填提示")]
    public void Emergency_three_fields_have_no_required_marker()
    {
        // Given 已點 nav-owners 進入飼主管理頁
        // When 點 btn-new-owner 開啟新增飼主表單
        _fx.ClickById("btn-new-owner");

        // Then 三個 emergency field 應存在（R1 改為非必填，Label 不應顯示 "*" 或 "必填"）
        // 只確認欄位可見（存在），不驗證 Label 文字（Label 控制項的 Name 屬性需用另外的 FlaUI 探查）
        var nameField = _fx.WaitForId("txt-owner-emergency-name");
        nameField.Should().NotBeNull("緊急聯絡人姓名欄位應存在");

        var phoneField = _fx.WaitForId("txt-owner-emergency-phone");
        phoneField.Should().NotBeNull("緊急聯絡人電話欄位應存在");

        var relField = _fx.WaitForId("txt-owner-emergency-relationship");
        relField.Should().NotBeNull("緊急聯絡人關係欄位應存在");

        // 確認 Label 中無 "*" 或 "必填" — 透過搜尋父容器的 Name 屬性
        // 若 XAML 中已移除必填標示，此斷言通過
        var asteriskEl = _fx.FindAnyContaining("* 緊急聯絡人");
        asteriskEl.Should().BeNull("緊急聯絡人欄位旁不應顯示「*」紅星標示（R1 已改為非必填）");

        var requiredEl = _fx.FindAnyContaining("必填緊急");
        requiredEl.Should().BeNull("緊急聯絡人欄位旁不應顯示「必填」字樣");
    }

    [Fact(DisplayName = "R1 / OwnerPageView 三欄全空仍可儲存成功")]
    public void Save_owner_with_three_empty_emergency_fields_does_not_throw()
    {
        // Given 點擊 btn-new-owner 開啟新增飼主表單
        _fx.ClickById("btn-new-owner");

        // When 輸入必填欄位、保留三欄空白、按下 btn-save-owner
        _fx.TypeInto("txt-owner-name", "王小明R1UI");
        _fx.TypeInto("txt-owner-national-id", "R1123456789");
        _fx.TypeInto("txt-owner-phone", "0912345678");
        _fx.TypeInto("txt-owner-address", "桃園市桃園區慈文路322巷5號");
        // 不輸入 emergency fields（保持空白）
        _fx.ClickById("btn-save-owner");
        Thread.Sleep(600);

        // Then 不應出現驗證錯誤對話框
        var errorDialog = _fx.MainWindow.ModalWindows.FirstOrDefault(w =>
            (w.Title ?? string.Empty).Contains("錯誤") ||
            (w.Title ?? string.Empty).Contains("必填") ||
            (w.Title ?? string.Empty).Contains("驗證"));
        errorDialog.Should().BeNull("不應出現驗證錯誤對話框");

        // 應出現儲存成功對話框（若出現）
        var successDialog = _fx.FindDialog("儲存成功", timeoutMs: 3000);
        // 允許無對話框（部分 ViewModel 不顯示成功 dialog）
        _fx.CloseAllDialogs();
    }

    [Fact(DisplayName = "R1 / 將既有飼主的緊急聯絡人三欄清空後仍可儲存",
        Skip = "需要先在 list-owners 中存在預建的 Owner 資料，依賴外部測試狀態；需 AppFixture seed 機制後補實作")]
    public void Clear_three_emergency_fields_on_existing_owner_saves()
    {
        // 此測試需要 list-owners 中已有一筆帶有緊急聯絡人的 Owner，
        // 測試環境隔離性不足（AppFixture 每次用新的空 DB），暫時略過。
        throw new InvalidOperationException("此 Fact 已設定 Skip，不應執行到此處");
    }
}
