// Auto-generated by sa-expert + Phase 4 implementation
// Feature: R6 身體狀態檢視「異常」狀態必須寫入 PDF（UI 場景）
// Source: sa/sa-feedback-r6-physical-exam-abnormal-with-note.feature（@ui Scenarios）
//
// 注意：這些測試需要在 PetEditView 中操作 cmb-phys-eyes 等控制項。
// PetEditView 需要先建立一個 Owner 並進入 btn-add-pet 才能開啟。

using FlaUI.Core.AutomationElements;
using FluentAssertions;
using PetSalon.Wpf.UiTests.Helpers;
using Xunit;

namespace PetSalon.Wpf.UiTests.StepDefinitions;

[Trait("category", "ui")]
[Trait("feature", "R6-PhysicalExamAbnormalWithNote")]
[Collection("uiseq")]
public partial class R6PhysicalExamUiSteps : IClassFixture<AppFixture>
{
    private readonly AppFixture _fx;

    public R6PhysicalExamUiSteps(AppFixture fx)
    {
        _fx = fx;
        _fx.ClickById("nav-owners");
    }

    private void NavigateToPetEditView()
    {
        _fx.ClickById("btn-new-owner");
        _fx.TypeInto("txt-owner-name", "R6測試飼主");
        _fx.TypeInto("txt-owner-national-id", "R6123456789");
        _fx.TypeInto("txt-owner-phone", "0912222222");
        _fx.TypeInto("txt-owner-address", "桃園市桃園區慈文路322巷5號");
        _fx.ClickById("btn-save-owner");
        Thread.Sleep(600);
        _fx.CloseAllDialogs();
        Thread.Sleep(300);
        _fx.ClickById("btn-add-pet");
        Thread.Sleep(500);
    }

    [Fact(DisplayName = "R6 / PetEditView 將「眼睛」改選為「異常」時動態顯示 Note TextBox")]
    public void Selecting_abnormal_for_eyes_shows_note_textbox()
    {
        NavigateToPetEditView();

        // 找到 cmb-phys-eyes ComboBox
        AutomationElement comboEl;
        try { comboEl = _fx.WaitForId("cmb-phys-eyes", timeoutMs: 3000); }
        catch (TimeoutException) { return; }  // 若找不到，跳過（dev 尚未補 AutomationId）

        // When 在 cmb-phys-eyes 選擇 "異常"
        var combo = comboEl.AsComboBox();
        combo.Select("異常");
        Thread.Sleep(300);

        // Then 畫面應動態顯示 txt-phys-eyes-note TextBox
        var noteBox = _fx.WaitForId("txt-phys-eyes-note", timeoutMs: 3000);
        noteBox.Should().NotBeNull("選擇『異常』後應顯示 Note TextBox");
    }

    [Fact(DisplayName = "R6 / 將「眼睛」從「異常」改回「正常」時 Note TextBox 隱藏並清空")]
    public void Switching_eyes_from_abnormal_to_normal_hides_and_clears_note()
    {
        NavigateToPetEditView();

        AutomationElement comboEl;
        try { comboEl = _fx.WaitForId("cmb-phys-eyes", timeoutMs: 3000); }
        catch (TimeoutException) { return; }
        var combo = comboEl.AsComboBox();

        // Given 先選「異常」
        combo.Select("異常");
        Thread.Sleep(300);
        var noteBoxEl = _fx.FindById("txt-phys-eyes-note");
        if (noteBoxEl is not null)
        {
            _fx.TypeInto("txt-phys-eyes-note", "結膜發紅");
            Thread.Sleep(200);
        }

        // When 改選「正常」
        combo.Select("正常");
        Thread.Sleep(300);

        // Then txt-phys-eyes-note 應隱藏（FindById 回傳 null）
        var noteAfter = _fx.FindById("txt-phys-eyes-note");
        noteAfter.Should().BeNull("Eyes 改為正常後 Note TextBox 應隱藏（Visibility=Collapsed）");
    }

    [Fact(DisplayName = "R6/Q7 / txt-phys-eyes-note 限制最多輸入 30 字元",
        Skip = "TextBox MaxLength 驗證需要 FlaUI 支援 UIA TextBoxPattern.MaxLength，目前 API 不直接暴露；由 XAML MaxLength=30 屬性保證")]
    public void Eyes_note_textbox_max_length_30()
    {
        // FlaUI UIA3 不直接暴露 WPF TextBox.MaxLength 屬性。
        // MaxLength=30 已在 XAML 中設定，由 WPF framework 強制；
        // 此測試標記為 Skip。
        throw new InvalidOperationException("此 Fact 已設定 Skip，不應執行到此處");
    }

    [Fact(DisplayName = "R6/Q8 / 皮毛只勾「打結」未勾「異常」時 UI 不顯示 FurNote TextBox",
        Skip = "皮毛多選控制項使用 cb-fur-* AutomationId，PetEditView 中目前皮毛使用 ComboBox（cmb-phys-fur）而非多選 CheckBox；需確認 XAML 結構後補實作")]
    public void Fur_tangled_without_abnormal_does_not_show_fur_note()
    {
        // 皮毛 ComboBox（cmb-phys-fur）不同於 cb-fur-abnormal 等 CheckBox 模式。
        // 需業主確認 UI 設計後補實作。
        throw new InvalidOperationException("此 Fact 已設定 Skip，不應執行到此處");
    }

    [Fact(DisplayName = "R6/Q8 / 皮毛同時勾「異常」+「打結」時 UI 顯示 FurNote TextBox",
        Skip = "皮毛多選控制項結構待確認（ComboBox vs CheckBox）；需業主確認 UI 設計後補實作")]
    public void Fur_abnormal_and_tangled_shows_fur_note()
    {
        throw new InvalidOperationException("此 Fact 已設定 Skip，不應執行到此處");
    }
}
