// Auto-generated by sa-expert + Phase 4 implementation
// Feature: R7 寵物病史新增「以上皆無」選項（UI 場景）
// Source: sa/sa-feedback-r7-medical-history-none-of-above.feature（@ui Scenarios）
//
// 注意：SA spec 使用英文 AutomationId（cb-medical-none-of-above、cb-medical-heart-disease 等），
// 但 PetEditView.xaml 使用 StringFormat='cb-medical-{0}' 其中 {0} 為中文選項名稱。
// 實際 AutomationId 為 cb-medical-以上皆無、cb-medical-心臟病 等。
// 此處改用正確的中文 AutomationId。
//
// PetEditView 從 OwnerPageView 點擊 btn-add-pet 進入。

using FlaUI.Core.AutomationElements;
using FluentAssertions;
using PetSalon.Wpf.UiTests.Helpers;
using Xunit;
// ReSharper disable PossibleNullReferenceException

namespace PetSalon.Wpf.UiTests.StepDefinitions;

[Trait("category", "ui")]
[Trait("feature", "R7-MedicalHistoryNoneOfAbove")]
[Collection("uiseq")]
public partial class R7MedicalHistoryUiSteps : IClassFixture<AppFixture>
{
    private readonly AppFixture _fx;
    // 實際 AutomationId 使用中文名稱
    private const string NoneOfAboveId = "cb-medical-以上皆無";
    private const string HeartDiseaseId = "cb-medical-心臟病";
    private const string AsthmaId = "cb-medical-氣喘";
    private const string OtherId = "cb-medical-其它";

    public R7MedicalHistoryUiSteps(AppFixture fx)
    {
        _fx = fx;
        _fx.ClickById("nav-owners");
    }

    private void NavigateToPetEditView()
    {
        _fx.ClickById("btn-new-owner");
        _fx.TypeInto("txt-owner-name", "R7測試飼主");
        _fx.TypeInto("txt-owner-national-id", "R7123456789");
        _fx.TypeInto("txt-owner-phone", "0912333333");
        _fx.TypeInto("txt-owner-address", "桃園市桃園區慈文路322巷5號");
        _fx.ClickById("btn-save-owner");
        Thread.Sleep(600);
        _fx.CloseAllDialogs();
        Thread.Sleep(300);
        _fx.ClickById("btn-add-pet");
        Thread.Sleep(500);
    }

    [Fact(DisplayName = "R7 / 病史區塊應包含「以上皆無」CheckBox")]
    public void Medical_history_block_contains_none_of_above_checkbox()
    {
        NavigateToPetEditView();

        // SA spec 用 cb-medical-none-of-above；實際 ID 為 cb-medical-以上皆無
        var none = _fx.FindById(NoneOfAboveId);
        none.Should().NotBeNull($"PetEditView 應有 {NoneOfAboveId} CheckBox");

        if (none is not null)
            none!.IsEnabled.Should().BeTrue("「以上皆無」CheckBox 應為可用狀態");
    }

    [Fact(DisplayName = "R7 / 勾選「以上皆無」時 ViewModel 自動取消其他 18 項病史")]
    public void Checking_none_of_above_unchecks_other_diseases()
    {
        NavigateToPetEditView();

        // Given 已勾選 cb-medical-心臟病 與 cb-medical-氣喘
        var heartCb = _fx.FindById(HeartDiseaseId);
        var asthmaCb = _fx.FindById(AsthmaId);
        if (heartCb is null || asthmaCb is null) return;

        heartCb!.AsCheckBox().IsChecked = true;
        asthmaCb!.AsCheckBox().IsChecked = true;
        Thread.Sleep(300);

        // When 勾選 cb-medical-以上皆無
        var noneCb = _fx.FindById(NoneOfAboveId);
        noneCb.Should().NotBeNull();
        if (noneCb is null) return;

        noneCb!.AsCheckBox().IsChecked = true;
        Thread.Sleep(300);

        // Then cb-medical-心臟病、cb-medical-氣喘 之 IsChecked 應為 false
        heartCb!.AsCheckBox().IsChecked.Should().BeFalse("勾選「以上皆無」後心臟病應取消");
        asthmaCb!.AsCheckBox().IsChecked.Should().BeFalse("勾選「以上皆無」後氣喘應取消");
    }

    [Fact(DisplayName = "R7 / 勾選任一具體病史時 ViewModel 自動取消「以上皆無」")]
    public void Checking_specific_disease_unchecks_none_of_above()
    {
        NavigateToPetEditView();

        // Given 已勾選 cb-medical-以上皆無
        var noneCb = _fx.FindById(NoneOfAboveId);
        if (noneCb is null) return;
        noneCb!.AsCheckBox().IsChecked = true;
        Thread.Sleep(300);

        // When 勾選 cb-medical-心臟病
        var heartCb = _fx.FindById(HeartDiseaseId);
        if (heartCb is null) return;
        heartCb!.AsCheckBox().IsChecked = true;
        Thread.Sleep(300);

        // Then cb-medical-以上皆無 之 IsChecked 應為 false
        noneCb!.AsCheckBox().IsChecked.Should().BeFalse("勾選具體病史後「以上皆無」應取消");
    }

    [Fact(DisplayName = "R7 / 「以上皆無」與「其它」互斥")]
    public void None_of_above_and_other_are_mutually_exclusive()
    {
        NavigateToPetEditView();

        // Given 已勾選 cb-medical-以上皆無
        var noneCb = _fx.FindById(NoneOfAboveId);
        if (noneCb is null) return;
        noneCb!.AsCheckBox().IsChecked = true;
        Thread.Sleep(300);

        // When 勾選 cb-medical-其它
        var otherCb = _fx.FindById(OtherId);
        if (otherCb is null) return;
        otherCb!.AsCheckBox().IsChecked = true;
        Thread.Sleep(300);

        // Then cb-medical-以上皆無 之 IsChecked 應為 false
        noneCb!.AsCheckBox().IsChecked.Should().BeFalse("勾選「其它」後「以上皆無」應取消");
    }

    [Fact(DisplayName = "R7 / 取消所有具體病史後陣列回到 [] 且後續 PDF 仍勾選「以上皆無」",
        Skip = "需儲存 Pet 後讀 DB 並產生 PDF 驗證；依賴 DB 直讀與 PDF 渲染流程，需完善後補實作")]
    public void After_clearing_all_diseases_pdf_still_checks_none_of_above()
    {
        throw new InvalidOperationException("此 Fact 已設定 Skip，不應執行到此處");
    }
}
